from django.core.management.base import BaseCommand
from django.utils.text import slugify
from core.models import ServiceCategory, ServiceSubcategory


CATEGORIES = [
    {
        'name': 'Plumbing',
        'icon': 'bi-wrench',
        'craigslist_section': 'services',
        'keywords': ['plumber', 'plumbing', 'drain', 'pipe', 'leak', 'water heater', 'sewer', 'faucet', 'toilet', 'clogged'],
        'google_terms': ['plumber', 'plumbing company', 'plumbing service'],
        'subs': ['Residential Plumbing', 'Commercial Plumbing', 'Emergency Plumbing', 'Drain Cleaning', 'Water Heater', 'Sewer Line', 'Gas Line'],
    },
    {
        'name': 'Electrical',
        'icon': 'bi-lightning',
        'craigslist_section': 'services',
        'keywords': ['electrician', 'electrical', 'wiring', 'outlet', 'circuit breaker', 'panel', 'lighting', 'electrical repair'],
        'google_terms': ['electrician', 'electrical contractor', 'electrical service'],
        'subs': ['Residential Electrical', 'Commercial Electrical', 'Panel Upgrade', 'Lighting Installation', 'Generator Installation'],
    },
    {
        'name': 'HVAC / Heating & Cooling',
        'icon': 'bi-thermometer-half',
        'craigslist_section': 'services',
        'keywords': ['hvac', 'heating', 'cooling', 'air conditioning', 'ac repair', 'furnace', 'heat pump', 'ductwork', 'ac unit'],
        'google_terms': ['hvac company', 'heating and cooling', 'ac repair'],
        'subs': ['AC Repair', 'Furnace Repair', 'Heat Pump', 'Ductwork', 'AC Installation', 'Boiler Repair'],
    },
    {
        'name': 'Handyman',
        'icon': 'bi-tools',
        'craigslist_section': 'services',
        'keywords': ['handyman', 'handy man', 'odd jobs', 'home repair', 'fix it', 'small repairs', 'maintenance'],
        'google_terms': ['handyman service', 'handyman near me'],
        'subs': ['General Repairs', 'Assembly', 'Mounting & Hanging', 'Minor Plumbing', 'Minor Electrical'],
    },
    {
        'name': 'Appliance Repair',
        'icon': 'bi-gear',
        'craigslist_section': 'services',
        'keywords': ['appliance repair', 'washer repair', 'dryer repair', 'dishwasher repair', 'refrigerator repair', 'oven repair', 'stove repair'],
        'google_terms': ['appliance repair', 'appliance service'],
        'subs': ['Washer/Dryer', 'Refrigerator', 'Dishwasher', 'Oven/Stove', 'Microwave'],
    },
    {
        'name': 'Locksmith',
        'icon': 'bi-key',
        'craigslist_section': 'services',
        'keywords': ['locksmith', 'locked out', 'lock change', 'key copy', 'rekey', 'deadbolt', 'lock replacement'],
        'google_terms': ['locksmith', 'locksmith service'],
        'subs': ['Residential Locksmith', 'Commercial Locksmith', 'Auto Locksmith', 'Emergency Lockout'],
    },
    {
        'name': 'Garage Door',
        'icon': 'bi-house-gear',
        'craigslist_section': 'services',
        'keywords': ['garage door', 'garage door repair', 'garage door opener', 'garage door installation', 'garage door spring'],
        'google_terms': ['garage door repair', 'garage door company'],
        'subs': ['Garage Door Repair', 'Garage Door Installation', 'Opener Repair', 'Spring Replacement'],
    },
    {
        'name': 'Home Security',
        'icon': 'bi-shield-lock',
        'craigslist_section': 'services',
        'keywords': ['home security', 'security system', 'alarm system', 'security camera', 'surveillance', 'smart lock'],
        'google_terms': ['home security installation', 'security system company'],
        'subs': ['Security System Install', 'Camera Installation', 'Smart Home Security'],
    },
    {
        'name': 'House Cleaning',
        'icon': 'bi-house-heart',
        'craigslist_section': 'services',
        'keywords': ['house cleaning', 'home cleaning', 'maid service', 'deep cleaning', 'cleaning service', 'housekeeper', 'residential cleaning'],
        'google_terms': ['house cleaning service', 'maid service', 'residential cleaning'],
        'subs': ['Regular Cleaning', 'Deep Cleaning', 'Move In/Out Cleaning', 'Post-Construction Cleaning'],
    },
    {
        'name': 'Commercial Cleaning',
        'icon': 'bi-building',
        'craigslist_section': 'services',
        'keywords': ['commercial cleaning', 'janitorial', 'office cleaning', 'business cleaning', 'industrial cleaning'],
        'google_terms': ['commercial cleaning service', 'janitorial service', 'office cleaning'],
        'subs': ['Office Cleaning', 'Restaurant Cleaning', 'Medical Facility Cleaning', 'Retail Cleaning', 'Floor Waxing/Stripping'],
    },
    {
        'name': 'Carpet Cleaning',
        'icon': 'bi-textarea',
        'craigslist_section': 'services',
        'keywords': ['carpet cleaning', 'carpet cleaner', 'rug cleaning', 'upholstery cleaning', 'steam cleaning'],
        'google_terms': ['carpet cleaning service', 'carpet cleaner'],
        'subs': ['Residential Carpet', 'Commercial Carpet', 'Rug Cleaning', 'Upholstery Cleaning'],
    },
    {
        'name': 'Window Cleaning',
        'icon': 'bi-window',
        'craigslist_section': 'services',
        'keywords': ['window cleaning', 'window washer', 'window washing', 'glass cleaning'],
        'google_terms': ['window cleaning service', 'window washer'],
        'subs': ['Residential Windows', 'Commercial Windows', 'High-Rise Windows'],
    },
    {
        'name': 'Pressure Washing',
        'icon': 'bi-droplet',
        'craigslist_section': 'services',
        'keywords': ['pressure washing', 'power washing', 'pressure wash', 'power wash', 'exterior cleaning'],
        'google_terms': ['pressure washing service', 'power washing'],
        'subs': ['House Washing', 'Driveway Cleaning', 'Deck Cleaning', 'Commercial Pressure Washing'],
    },
    {
        'name': 'Pool Cleaning',
        'icon': 'bi-water',
        'craigslist_section': 'services',
        'keywords': ['pool cleaning', 'pool service', 'pool maintenance', 'pool repair', 'swimming pool'],
        'google_terms': ['pool cleaning service', 'pool maintenance'],
        'subs': ['Weekly Pool Service', 'Pool Opening/Closing', 'Pool Repair', 'Equipment Repair'],
    },
    {
        'name': 'Gutter Cleaning',
        'icon': 'bi-funnel',
        'craigslist_section': 'services',
        'keywords': ['gutter cleaning', 'gutter repair', 'gutter installation', 'gutter guard', 'downspout'],
        'google_terms': ['gutter cleaning service', 'gutter repair'],
        'subs': ['Gutter Cleaning', 'Gutter Repair', 'Gutter Guard Installation'],
    },
    {
        'name': 'Landscaping',
        'icon': 'bi-tree',
        'craigslist_section': 'services',
        'keywords': ['landscaping', 'landscape design', 'garden design', 'hardscaping', 'retaining wall', 'landscape installation'],
        'google_terms': ['landscaping company', 'landscape design'],
        'subs': ['Landscape Design', 'Hardscaping', 'Softscaping', 'Retaining Walls', 'Outdoor Lighting'],
    },
    {
        'name': 'Lawn Care',
        'icon': 'bi-flower1',
        'craigslist_section': 'services',
        'keywords': ['lawn care', 'lawn mowing', 'grass cutting', 'lawn service', 'lawn maintenance', 'yard work', 'lawn treatment'],
        'google_terms': ['lawn care service', 'lawn mowing service'],
        'subs': ['Mowing', 'Fertilization', 'Weed Control', 'Aeration', 'Overseeding'],
    },
    {
        'name': 'Tree Service',
        'icon': 'bi-tree-fill',
        'craigslist_section': 'services',
        'keywords': ['tree service', 'tree removal', 'tree trimming', 'tree cutting', 'stump grinding', 'arborist', 'tree pruning'],
        'google_terms': ['tree service', 'tree removal', 'arborist'],
        'subs': ['Tree Removal', 'Tree Trimming', 'Stump Grinding', 'Emergency Tree Service'],
    },
    {
        'name': 'Fencing',
        'icon': 'bi-border-outer',
        'craigslist_section': 'services',
        'keywords': ['fencing', 'fence installation', 'fence repair', 'fence company', 'privacy fence', 'chain link fence', 'wood fence'],
        'google_terms': ['fence company', 'fence installation'],
        'subs': ['Wood Fence', 'Vinyl Fence', 'Chain Link', 'Aluminum Fence', 'Fence Repair'],
    },
    {
        'name': 'Concrete & Masonry',
        'icon': 'bi-bricks',
        'craigslist_section': 'services',
        'keywords': ['concrete', 'masonry', 'brick', 'stone', 'patio', 'sidewalk', 'driveway', 'foundation', 'block wall'],
        'google_terms': ['concrete contractor', 'masonry contractor'],
        'subs': ['Concrete Pouring', 'Brick Work', 'Stone Work', 'Foundation Repair', 'Stamped Concrete'],
    },
    {
        'name': 'Paving & Asphalt',
        'icon': 'bi-signpost-2',
        'craigslist_section': 'services',
        'keywords': ['paving', 'asphalt', 'driveway paving', 'parking lot', 'sealcoating', 'blacktop'],
        'google_terms': ['paving company', 'asphalt contractor'],
        'subs': ['Driveway Paving', 'Parking Lot Paving', 'Sealcoating', 'Asphalt Repair'],
    },
    {
        'name': 'Snow Removal',
        'icon': 'bi-snow',
        'craigslist_section': 'services',
        'keywords': ['snow removal', 'snow plowing', 'ice removal', 'salting', 'snow clearing', 'winter maintenance'],
        'google_terms': ['snow removal service', 'snow plowing'],
        'subs': ['Residential Snow Removal', 'Commercial Snow Removal', 'Salting/De-icing'],
    },
    {
        'name': 'Irrigation',
        'icon': 'bi-moisture',
        'craigslist_section': 'services',
        'keywords': ['irrigation', 'sprinkler', 'sprinkler system', 'sprinkler repair', 'drip irrigation'],
        'google_terms': ['irrigation company', 'sprinkler installation'],
        'subs': ['Sprinkler Installation', 'Sprinkler Repair', 'Drip Irrigation', 'Winterization'],
    },
    {
        'name': 'Deck & Patio',
        'icon': 'bi-house',
        'craigslist_section': 'services',
        'keywords': ['deck', 'patio', 'deck building', 'deck repair', 'deck staining', 'pergola', 'outdoor living'],
        'google_terms': ['deck builder', 'patio contractor'],
        'subs': ['Deck Building', 'Deck Repair', 'Deck Staining', 'Pergola', 'Patio Construction'],
    },
    {
        'name': 'General Contractor',
        'icon': 'bi-hammer',
        'craigslist_section': 'services',
        'keywords': ['general contractor', 'contractor', 'renovation', 'remodel', 'construction', 'home improvement', 'addition'],
        'google_terms': ['general contractor', 'home renovation contractor'],
        'subs': ['Home Renovation', 'Room Addition', 'Commercial Construction', 'Project Management'],
    },
    {
        'name': 'Roofing',
        'icon': 'bi-house-up',
        'craigslist_section': 'services',
        'keywords': ['roofing', 'roof repair', 'roof replacement', 'roofer', 'shingles', 'roof leak', 'new roof', 'roof inspection'],
        'google_terms': ['roofing company', 'roofer', 'roof repair'],
        'subs': ['Roof Repair', 'Roof Replacement', 'Flat Roof', 'Metal Roof', 'Roof Inspection'],
    },
    {
        'name': 'Painting',
        'icon': 'bi-paint-bucket',
        'craigslist_section': 'services',
        'keywords': ['painting', 'painter', 'interior painting', 'exterior painting', 'house painting', 'paint job', 'staining'],
        'google_terms': ['painting company', 'house painter', 'painting contractor'],
        'subs': ['Interior Painting', 'Exterior Painting', 'Cabinet Painting', 'Staining', 'Commercial Painting'],
    },
    {
        'name': 'Flooring',
        'icon': 'bi-grid-3x3',
        'craigslist_section': 'services',
        'keywords': ['flooring', 'floor installation', 'hardwood floor', 'laminate', 'vinyl flooring', 'tile floor', 'carpet installation'],
        'google_terms': ['flooring company', 'floor installation'],
        'subs': ['Hardwood', 'Laminate', 'Vinyl/LVP', 'Tile', 'Carpet Installation', 'Floor Refinishing'],
    },
    {
        'name': 'Drywall',
        'icon': 'bi-square',
        'craigslist_section': 'services',
        'keywords': ['drywall', 'sheetrock', 'drywall repair', 'drywall installation', 'plastering', 'wall repair'],
        'google_terms': ['drywall contractor', 'drywall repair'],
        'subs': ['Drywall Installation', 'Drywall Repair', 'Texturing', 'Plastering'],
    },
    {
        'name': 'Tile',
        'icon': 'bi-grid',
        'craigslist_section': 'services',
        'keywords': ['tile', 'tile installation', 'tile work', 'backsplash', 'floor tile', 'bathroom tile', 'shower tile'],
        'google_terms': ['tile installer', 'tile contractor'],
        'subs': ['Floor Tile', 'Bathroom Tile', 'Kitchen Backsplash', 'Shower Tile', 'Mosaic'],
    },
    {
        'name': 'Kitchen Remodeling',
        'icon': 'bi-cup-hot',
        'craigslist_section': 'services',
        'keywords': ['kitchen remodel', 'kitchen renovation', 'kitchen cabinets', 'countertop', 'kitchen design', 'kitchen update'],
        'google_terms': ['kitchen remodeling', 'kitchen renovation contractor'],
        'subs': ['Full Kitchen Remodel', 'Cabinet Refacing', 'Countertop Installation', 'Kitchen Island'],
    },
    {
        'name': 'Bathroom Remodeling',
        'icon': 'bi-droplet-half',
        'craigslist_section': 'services',
        'keywords': ['bathroom remodel', 'bathroom renovation', 'shower remodel', 'bathtub', 'bathroom design', 'bathroom update'],
        'google_terms': ['bathroom remodeling', 'bathroom renovation contractor'],
        'subs': ['Full Bathroom Remodel', 'Shower Conversion', 'Vanity Installation', 'Tub-to-Shower'],
    },
    {
        'name': 'Basement Finishing',
        'icon': 'bi-layers',
        'craigslist_section': 'services',
        'keywords': ['basement finishing', 'basement remodel', 'basement renovation', 'finished basement', 'basement waterproofing'],
        'google_terms': ['basement finishing contractor', 'basement remodeling'],
        'subs': ['Basement Finishing', 'Basement Waterproofing', 'Egress Window', 'Basement Bathroom'],
    },
    {
        'name': 'Siding',
        'icon': 'bi-border-all',
        'craigslist_section': 'services',
        'keywords': ['siding', 'siding installation', 'vinyl siding', 'siding repair', 'fiber cement', 'hardie board'],
        'google_terms': ['siding contractor', 'siding installation'],
        'subs': ['Vinyl Siding', 'Fiber Cement', 'Wood Siding', 'Siding Repair'],
    },
    {
        'name': 'Windows & Doors',
        'icon': 'bi-door-open',
        'craigslist_section': 'services',
        'keywords': ['window installation', 'door installation', 'replacement windows', 'new windows', 'entry door', 'sliding door', 'window replacement'],
        'google_terms': ['window installation', 'door installation company'],
        'subs': ['Window Replacement', 'Door Installation', 'Storm Doors', 'Patio Doors', 'Skylights'],
    },
    {
        'name': 'Pest Control',
        'icon': 'bi-bug',
        'craigslist_section': 'services',
        'keywords': ['pest control', 'exterminator', 'bug spray', 'termite', 'ant control', 'rodent control', 'bed bug', 'mosquito'],
        'google_terms': ['pest control service', 'exterminator'],
        'subs': ['General Pest Control', 'Termite Treatment', 'Rodent Control', 'Bed Bug Treatment', 'Mosquito Control', 'Wildlife Removal'],
    },
    {
        'name': 'Junk Removal',
        'icon': 'bi-trash3',
        'craigslist_section': 'services',
        'keywords': ['junk removal', 'hauling', 'trash removal', 'debris removal', 'cleanout', 'estate cleanout', 'dump run'],
        'google_terms': ['junk removal service', 'hauling service'],
        'subs': ['Residential Junk Removal', 'Commercial Junk Removal', 'Estate Cleanout', 'Construction Debris'],
    },
    {
        'name': 'Moving',
        'icon': 'bi-truck',
        'craigslist_section': 'services',
        'keywords': ['moving', 'movers', 'moving company', 'relocation', 'packing', 'moving help', 'furniture moving'],
        'google_terms': ['moving company', 'movers near me'],
        'subs': ['Local Moving', 'Long Distance Moving', 'Packing Services', 'Piano Moving', 'Office Moving'],
    },
    {
        'name': 'Water Damage Restoration',
        'icon': 'bi-tsunami',
        'craigslist_section': 'services',
        'keywords': ['water damage', 'flood damage', 'water restoration', 'water cleanup', 'water extraction', 'flood cleanup'],
        'google_terms': ['water damage restoration', 'flood cleanup'],
        'subs': ['Water Extraction', 'Flood Cleanup', 'Structural Drying', 'Sewage Cleanup'],
    },
    {
        'name': 'Mold Remediation',
        'icon': 'bi-virus',
        'craigslist_section': 'services',
        'keywords': ['mold', 'mold removal', 'mold remediation', 'mold testing', 'mold inspection', 'black mold'],
        'google_terms': ['mold remediation', 'mold removal service'],
        'subs': ['Mold Testing', 'Mold Removal', 'Mold Prevention'],
    },
    {
        'name': 'Insulation',
        'icon': 'bi-thermometer-snow',
        'craigslist_section': 'services',
        'keywords': ['insulation', 'spray foam', 'blown-in insulation', 'attic insulation', 'wall insulation'],
        'google_terms': ['insulation contractor', 'insulation company'],
        'subs': ['Spray Foam', 'Blown-In', 'Batt Insulation', 'Attic Insulation'],
    },
    {
        'name': 'Solar Installation',
        'icon': 'bi-sun',
        'craigslist_section': 'services',
        'keywords': ['solar', 'solar panel', 'solar installation', 'solar energy', 'solar power', 'solar company'],
        'google_terms': ['solar installation', 'solar panel company'],
        'subs': ['Residential Solar', 'Commercial Solar', 'Solar Battery', 'Solar Maintenance'],
    },
    {
        'name': 'EV Charger Installation',
        'icon': 'bi-ev-station',
        'craigslist_section': 'services',
        'keywords': ['ev charger', 'electric vehicle charger', 'charging station', 'tesla charger', 'level 2 charger'],
        'google_terms': ['ev charger installation', 'electric vehicle charger installer'],
        'subs': ['Home EV Charger', 'Commercial EV Charger'],
    },
    {
        'name': 'Chimney Sweep',
        'icon': 'bi-fire',
        'craigslist_section': 'services',
        'keywords': ['chimney sweep', 'chimney cleaning', 'chimney repair', 'chimney inspection', 'fireplace repair'],
        'google_terms': ['chimney sweep', 'chimney cleaning service'],
        'subs': ['Chimney Cleaning', 'Chimney Repair', 'Chimney Inspection', 'Chimney Cap'],
    },
    {
        'name': 'Septic Service',
        'icon': 'bi-recycle',
        'craigslist_section': 'services',
        'keywords': ['septic', 'septic tank', 'septic pumping', 'septic repair', 'septic installation', 'cesspool'],
        'google_terms': ['septic service', 'septic pumping'],
        'subs': ['Septic Pumping', 'Septic Repair', 'Septic Installation', 'Septic Inspection'],
    },
    {
        'name': 'Auto Repair',
        'icon': 'bi-car-front',
        'craigslist_section': 'services',
        'keywords': ['auto repair', 'car repair', 'mechanic', 'auto mechanic', 'brake repair', 'engine repair', 'transmission'],
        'google_terms': ['auto repair shop', 'car mechanic'],
        'subs': ['Engine Repair', 'Brake Service', 'Transmission', 'Diagnostics', 'Oil Change'],
    },
    {
        'name': 'Auto Body',
        'icon': 'bi-car-front-fill',
        'craigslist_section': 'services',
        'keywords': ['auto body', 'body shop', 'collision repair', 'dent repair', 'paint job', 'fender repair'],
        'google_terms': ['auto body shop', 'collision repair'],
        'subs': ['Collision Repair', 'Dent Repair', 'Auto Painting', 'Frame Repair'],
    },
    {
        'name': 'Towing',
        'icon': 'bi-truck-front',
        'craigslist_section': 'services',
        'keywords': ['towing', 'tow truck', 'roadside assistance', 'car towing', 'flatbed tow'],
        'google_terms': ['towing service', 'tow truck'],
        'subs': ['Emergency Towing', 'Long Distance Towing', 'Flatbed Towing', 'Roadside Assistance'],
    },
    {
        'name': 'Auto Detailing',
        'icon': 'bi-stars',
        'craigslist_section': 'services',
        'keywords': ['auto detailing', 'car detailing', 'car wash', 'paint correction', 'ceramic coating', 'interior detailing'],
        'google_terms': ['auto detailing', 'car detailing service'],
        'subs': ['Interior Detailing', 'Exterior Detailing', 'Ceramic Coating', 'Paint Correction'],
    },
    {
        'name': 'Windshield Repair',
        'icon': 'bi-shield-shaded',
        'craigslist_section': 'services',
        'keywords': ['windshield repair', 'windshield replacement', 'auto glass', 'cracked windshield', 'chip repair'],
        'google_terms': ['windshield repair', 'auto glass replacement'],
        'subs': ['Chip Repair', 'Windshield Replacement', 'Side Window', 'Rear Window'],
    },
    {
        'name': 'Mobile Mechanic',
        'icon': 'bi-tools',
        'craigslist_section': 'services',
        'keywords': ['mobile mechanic', 'mobile auto repair', 'on-site mechanic', 'mobile car repair'],
        'google_terms': ['mobile mechanic', 'mobile auto repair'],
        'subs': ['Mobile Oil Change', 'Mobile Brake Service', 'Mobile Diagnostics', 'Mobile Battery Service'],
    },
    {
        'name': 'Construction Cleanup',
        'icon': 'bi-building-gear',
        'craigslist_section': 'services',
        'keywords': ['construction cleanup', 'post construction cleaning', 'builder cleanup', 'construction debris'],
        'google_terms': ['construction cleanup service', 'post construction cleaning'],
        'subs': ['Rough Clean', 'Final Clean', 'Debris Removal'],
    },
]


class Command(BaseCommand):
    help = 'Seed service categories and subcategories'

    def handle(self, *args, **options):
        created_count = 0
        for i, cat_data in enumerate(CATEGORIES):
            cat, created = ServiceCategory.objects.update_or_create(
                slug=slugify(cat_data['name']),
                defaults={
                    'name': cat_data['name'],
                    'icon': cat_data.get('icon', ''),
                    'craigslist_section': cat_data.get('craigslist_section', ''),
                    'default_keywords': cat_data.get('keywords', []),
                    'google_maps_terms': cat_data.get('google_terms', []),
                    'sort_order': i,
                    'is_active': True,
                }
            )
            if created:
                created_count += 1

            for sub_name in cat_data.get('subs', []):
                ServiceSubcategory.objects.update_or_create(
                    category=cat,
                    slug=slugify(sub_name),
                    defaults={'name': sub_name}
                )

        total = ServiceCategory.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created_count} new categories (total: {total}) with subcategories'
        ))
