from django.core.management.base import BaseCommand
from django.utils.text import slugify
from core.models import ServiceCategory, ServiceSubcategory


CATEGORIES = [
    # ── Home Services & Repair ─────────────────────────────────
    {
        'name': 'Plumbing',
        'group': 'home_services',
        'icon': 'bi-wrench',
        'craigslist_section': 'services',
        'keywords': ['plumber', 'plumbing', 'drain', 'pipe', 'leak', 'water heater', 'sewer', 'faucet', 'toilet', 'clogged'],
        'google_terms': ['plumber', 'plumbing company', 'plumbing service'],
        'subs': ['Residential Plumbing', 'Commercial Plumbing', 'Emergency Plumbing', 'Drain Cleaning', 'Water Heater', 'Sewer Line', 'Gas Line'],
    },
    {
        'name': 'Electrical',
        'group': 'home_services',
        'icon': 'bi-lightning',
        'craigslist_section': 'services',
        'keywords': ['electrician', 'electrical', 'wiring', 'outlet', 'circuit breaker', 'panel', 'lighting', 'electrical repair'],
        'google_terms': ['electrician', 'electrical contractor', 'electrical service'],
        'subs': ['Residential Electrical', 'Commercial Electrical', 'Panel Upgrade', 'Lighting Installation', 'Generator Installation'],
    },
    {
        'name': 'HVAC / Heating & Cooling',
        'group': 'home_services',
        'icon': 'bi-thermometer-half',
        'craigslist_section': 'services',
        'keywords': ['hvac', 'heating', 'cooling', 'air conditioning', 'ac repair', 'furnace', 'heat pump', 'ductwork', 'ac unit'],
        'google_terms': ['hvac company', 'heating and cooling', 'ac repair'],
        'subs': ['AC Repair', 'Furnace Repair', 'Heat Pump', 'Ductwork', 'AC Installation', 'Boiler Repair'],
    },
    {
        'name': 'Handyman',
        'group': 'home_services',
        'icon': 'bi-tools',
        'craigslist_section': 'services',
        'keywords': ['handyman', 'handy man', 'odd jobs', 'home repair', 'fix it', 'small repairs', 'maintenance'],
        'google_terms': ['handyman service', 'handyman near me'],
        'subs': ['General Repairs', 'Assembly', 'Mounting & Hanging', 'Minor Plumbing', 'Minor Electrical'],
    },
    {
        'name': 'Appliance Repair',
        'group': 'home_services',
        'icon': 'bi-gear',
        'craigslist_section': 'services',
        'keywords': ['appliance repair', 'washer repair', 'dryer repair', 'dishwasher repair', 'refrigerator repair', 'oven repair', 'stove repair'],
        'google_terms': ['appliance repair', 'appliance service'],
        'subs': ['Washer/Dryer', 'Refrigerator', 'Dishwasher', 'Oven/Stove', 'Microwave'],
    },
    {
        'name': 'Locksmith',
        'group': 'home_services',
        'icon': 'bi-key',
        'craigslist_section': 'services',
        'keywords': ['locksmith', 'locked out', 'lock change', 'key copy', 'rekey', 'deadbolt', 'lock replacement'],
        'google_terms': ['locksmith', 'locksmith service'],
        'subs': ['Residential Locksmith', 'Commercial Locksmith', 'Auto Locksmith', 'Emergency Lockout'],
    },
    {
        'name': 'Garage Door',
        'group': 'home_services',
        'icon': 'bi-house-gear',
        'craigslist_section': 'services',
        'keywords': ['garage door', 'garage door repair', 'garage door opener', 'garage door installation', 'garage door spring'],
        'google_terms': ['garage door repair', 'garage door company'],
        'subs': ['Garage Door Repair', 'Garage Door Installation', 'Opener Repair', 'Spring Replacement'],
    },
    {
        'name': 'Home Security',
        'group': 'home_services',
        'icon': 'bi-shield-lock',
        'craigslist_section': 'services',
        'keywords': ['home security', 'security system', 'alarm system', 'security camera', 'surveillance', 'smart lock'],
        'google_terms': ['home security installation', 'security system company'],
        'subs': ['Security System Install', 'Camera Installation', 'Smart Home Security'],
    },
    {
        'name': 'Pest Control',
        'group': 'home_services',
        'icon': 'bi-bug',
        'craigslist_section': 'services',
        'keywords': ['pest control', 'exterminator', 'bug spray', 'termite', 'ant control', 'rodent control', 'bed bug', 'mosquito'],
        'google_terms': ['pest control service', 'exterminator'],
        'subs': ['General Pest Control', 'Termite Treatment', 'Rodent Control', 'Bed Bug Treatment', 'Mosquito Control', 'Wildlife Removal'],
    },
    {
        'name': 'Water Damage Restoration',
        'group': 'home_services',
        'icon': 'bi-tsunami',
        'craigslist_section': 'services',
        'keywords': ['water damage', 'flood damage', 'water restoration', 'water cleanup', 'water extraction', 'flood cleanup'],
        'google_terms': ['water damage restoration', 'flood cleanup'],
        'subs': ['Water Extraction', 'Flood Cleanup', 'Structural Drying', 'Sewage Cleanup'],
    },
    {
        'name': 'Mold Remediation',
        'group': 'home_services',
        'icon': 'bi-virus',
        'craigslist_section': 'services',
        'keywords': ['mold', 'mold removal', 'mold remediation', 'mold testing', 'mold inspection', 'black mold'],
        'google_terms': ['mold remediation', 'mold removal service'],
        'subs': ['Mold Testing', 'Mold Removal', 'Mold Prevention'],
    },
    {
        'name': 'Insulation',
        'group': 'home_services',
        'icon': 'bi-thermometer-snow',
        'craigslist_section': 'services',
        'keywords': ['insulation', 'spray foam', 'blown-in insulation', 'attic insulation', 'wall insulation'],
        'google_terms': ['insulation contractor', 'insulation company'],
        'subs': ['Spray Foam', 'Blown-In', 'Batt Insulation', 'Attic Insulation'],
    },
    {
        'name': 'Solar Installation',
        'group': 'home_services',
        'icon': 'bi-sun',
        'craigslist_section': 'services',
        'keywords': ['solar', 'solar panel', 'solar installation', 'solar energy', 'solar power', 'solar company'],
        'google_terms': ['solar installation', 'solar panel company'],
        'subs': ['Residential Solar', 'Commercial Solar', 'Solar Battery', 'Solar Maintenance'],
    },
    {
        'name': 'EV Charger Installation',
        'group': 'home_services',
        'icon': 'bi-ev-station',
        'craigslist_section': 'services',
        'keywords': ['ev charger', 'electric vehicle charger', 'charging station', 'tesla charger', 'level 2 charger'],
        'google_terms': ['ev charger installation', 'electric vehicle charger installer'],
        'subs': ['Home EV Charger', 'Commercial EV Charger'],
    },
    {
        'name': 'Chimney Sweep',
        'group': 'home_services',
        'icon': 'bi-fire',
        'craigslist_section': 'services',
        'keywords': ['chimney sweep', 'chimney cleaning', 'chimney repair', 'chimney inspection', 'fireplace repair'],
        'google_terms': ['chimney sweep', 'chimney cleaning service'],
        'subs': ['Chimney Cleaning', 'Chimney Repair', 'Chimney Inspection', 'Chimney Cap'],
    },
    {
        'name': 'Septic Service',
        'group': 'home_services',
        'icon': 'bi-recycle',
        'craigslist_section': 'services',
        'keywords': ['septic', 'septic tank', 'septic pumping', 'septic repair', 'septic installation', 'cesspool'],
        'google_terms': ['septic service', 'septic pumping'],
        'subs': ['Septic Pumping', 'Septic Repair', 'Septic Installation', 'Septic Inspection'],
    },

    # ── Cleaning Services ──────────────────────────────────────
    {
        'name': 'House Cleaning',
        'group': 'cleaning',
        'icon': 'bi-house-heart',
        'craigslist_section': 'services',
        'keywords': ['house cleaning', 'home cleaning', 'maid service', 'deep cleaning', 'cleaning service', 'housekeeper', 'residential cleaning'],
        'google_terms': ['house cleaning service', 'maid service', 'residential cleaning'],
        'subs': ['Regular Cleaning', 'Deep Cleaning', 'Move In/Out Cleaning', 'Post-Construction Cleaning'],
    },
    {
        'name': 'Commercial Cleaning',
        'group': 'cleaning',
        'icon': 'bi-building',
        'craigslist_section': 'services',
        'keywords': ['commercial cleaning', 'janitorial', 'office cleaning', 'business cleaning', 'industrial cleaning'],
        'google_terms': ['commercial cleaning service', 'janitorial service', 'office cleaning'],
        'subs': ['Office Cleaning', 'Restaurant Cleaning', 'Medical Facility Cleaning', 'Retail Cleaning', 'Floor Waxing/Stripping'],
    },
    {
        'name': 'Carpet Cleaning',
        'group': 'cleaning',
        'icon': 'bi-textarea',
        'craigslist_section': 'services',
        'keywords': ['carpet cleaning', 'carpet cleaner', 'rug cleaning', 'upholstery cleaning', 'steam cleaning'],
        'google_terms': ['carpet cleaning service', 'carpet cleaner'],
        'subs': ['Residential Carpet', 'Commercial Carpet', 'Rug Cleaning', 'Upholstery Cleaning'],
    },
    {
        'name': 'Window Cleaning',
        'group': 'cleaning',
        'icon': 'bi-window',
        'craigslist_section': 'services',
        'keywords': ['window cleaning', 'window washer', 'window washing', 'glass cleaning'],
        'google_terms': ['window cleaning service', 'window washer'],
        'subs': ['Residential Windows', 'Commercial Windows', 'High-Rise Windows'],
    },
    {
        'name': 'Pressure Washing',
        'group': 'cleaning',
        'icon': 'bi-droplet',
        'craigslist_section': 'services',
        'keywords': ['pressure washing', 'power washing', 'pressure wash', 'power wash', 'exterior cleaning'],
        'google_terms': ['pressure washing service', 'power washing'],
        'subs': ['House Washing', 'Driveway Cleaning', 'Deck Cleaning', 'Commercial Pressure Washing'],
    },
    {
        'name': 'Pool Cleaning',
        'group': 'cleaning',
        'icon': 'bi-water',
        'craigslist_section': 'services',
        'keywords': ['pool cleaning', 'pool service', 'pool maintenance', 'pool repair', 'swimming pool'],
        'google_terms': ['pool cleaning service', 'pool maintenance'],
        'subs': ['Weekly Pool Service', 'Pool Opening/Closing', 'Pool Repair', 'Equipment Repair'],
    },
    {
        'name': 'Gutter Cleaning',
        'group': 'cleaning',
        'icon': 'bi-funnel',
        'craigslist_section': 'services',
        'keywords': ['gutter cleaning', 'gutter repair', 'gutter installation', 'gutter guard', 'downspout'],
        'google_terms': ['gutter cleaning service', 'gutter repair'],
        'subs': ['Gutter Cleaning', 'Gutter Repair', 'Gutter Guard Installation'],
    },
    {
        'name': 'Construction Cleanup',
        'group': 'cleaning',
        'icon': 'bi-building-gear',
        'craigslist_section': 'services',
        'keywords': ['construction cleanup', 'post construction cleaning', 'builder cleanup', 'construction debris'],
        'google_terms': ['construction cleanup service', 'post construction cleaning'],
        'subs': ['Rough Clean', 'Final Clean', 'Debris Removal'],
    },
    {
        'name': 'Junk Removal',
        'group': 'cleaning',
        'icon': 'bi-trash3',
        'craigslist_section': 'services',
        'keywords': ['junk removal', 'hauling', 'trash removal', 'debris removal', 'cleanout', 'estate cleanout', 'dump run'],
        'google_terms': ['junk removal service', 'hauling service'],
        'subs': ['Residential Junk Removal', 'Commercial Junk Removal', 'Estate Cleanout', 'Construction Debris'],
    },

    # ── Outdoor & Landscaping ──────────────────────────────────
    {
        'name': 'Landscaping',
        'group': 'outdoor',
        'icon': 'bi-tree',
        'craigslist_section': 'services',
        'keywords': ['landscaping', 'landscape design', 'garden design', 'hardscaping', 'retaining wall', 'landscape installation'],
        'google_terms': ['landscaping company', 'landscape design'],
        'subs': ['Landscape Design', 'Hardscaping', 'Softscaping', 'Retaining Walls', 'Outdoor Lighting'],
    },
    {
        'name': 'Lawn Care',
        'group': 'outdoor',
        'icon': 'bi-flower1',
        'craigslist_section': 'services',
        'keywords': ['lawn care', 'lawn mowing', 'grass cutting', 'lawn service', 'lawn maintenance', 'yard work', 'lawn treatment'],
        'google_terms': ['lawn care service', 'lawn mowing service'],
        'subs': ['Mowing', 'Fertilization', 'Weed Control', 'Aeration', 'Overseeding'],
    },
    {
        'name': 'Tree Service',
        'group': 'outdoor',
        'icon': 'bi-tree-fill',
        'craigslist_section': 'services',
        'keywords': ['tree service', 'tree removal', 'tree trimming', 'tree cutting', 'stump grinding', 'arborist', 'tree pruning'],
        'google_terms': ['tree service', 'tree removal', 'arborist'],
        'subs': ['Tree Removal', 'Tree Trimming', 'Stump Grinding', 'Emergency Tree Service'],
    },
    {
        'name': 'Fencing',
        'group': 'outdoor',
        'icon': 'bi-border-outer',
        'craigslist_section': 'services',
        'keywords': ['fencing', 'fence installation', 'fence repair', 'fence company', 'privacy fence', 'chain link fence', 'wood fence'],
        'google_terms': ['fence company', 'fence installation'],
        'subs': ['Wood Fence', 'Vinyl Fence', 'Chain Link', 'Aluminum Fence', 'Fence Repair'],
    },
    {
        'name': 'Concrete & Masonry',
        'group': 'outdoor',
        'icon': 'bi-bricks',
        'craigslist_section': 'services',
        'keywords': ['concrete', 'masonry', 'brick', 'stone', 'patio', 'sidewalk', 'driveway', 'foundation', 'block wall'],
        'google_terms': ['concrete contractor', 'masonry contractor'],
        'subs': ['Concrete Pouring', 'Brick Work', 'Stone Work', 'Foundation Repair', 'Stamped Concrete'],
    },
    {
        'name': 'Paving & Asphalt',
        'group': 'outdoor',
        'icon': 'bi-signpost-2',
        'craigslist_section': 'services',
        'keywords': ['paving', 'asphalt', 'driveway paving', 'parking lot', 'sealcoating', 'blacktop'],
        'google_terms': ['paving company', 'asphalt contractor'],
        'subs': ['Driveway Paving', 'Parking Lot Paving', 'Sealcoating', 'Asphalt Repair'],
    },
    {
        'name': 'Snow Removal',
        'group': 'outdoor',
        'icon': 'bi-snow',
        'craigslist_section': 'services',
        'keywords': ['snow removal', 'snow plowing', 'ice removal', 'salting', 'snow clearing', 'winter maintenance'],
        'google_terms': ['snow removal service', 'snow plowing'],
        'subs': ['Residential Snow Removal', 'Commercial Snow Removal', 'Salting/De-icing'],
    },
    {
        'name': 'Irrigation',
        'group': 'outdoor',
        'icon': 'bi-moisture',
        'craigslist_section': 'services',
        'keywords': ['irrigation', 'sprinkler', 'sprinkler system', 'sprinkler repair', 'drip irrigation'],
        'google_terms': ['irrigation company', 'sprinkler installation'],
        'subs': ['Sprinkler Installation', 'Sprinkler Repair', 'Drip Irrigation', 'Winterization'],
    },
    {
        'name': 'Deck & Patio',
        'group': 'outdoor',
        'icon': 'bi-house',
        'craigslist_section': 'services',
        'keywords': ['deck', 'patio', 'deck building', 'deck repair', 'deck staining', 'pergola', 'outdoor living'],
        'google_terms': ['deck builder', 'patio contractor'],
        'subs': ['Deck Building', 'Deck Repair', 'Deck Staining', 'Pergola', 'Patio Construction'],
    },

    # ── Construction & Remodeling ──────────────────────────────
    {
        'name': 'General Contractor',
        'group': 'construction',
        'icon': 'bi-hammer',
        'craigslist_section': 'services',
        'keywords': ['general contractor', 'contractor', 'renovation', 'remodel', 'construction', 'home improvement', 'addition'],
        'google_terms': ['general contractor', 'home renovation contractor'],
        'subs': ['Home Renovation', 'Room Addition', 'Commercial Construction', 'Project Management'],
    },
    {
        'name': 'Roofing',
        'group': 'construction',
        'icon': 'bi-house-up',
        'craigslist_section': 'services',
        'keywords': ['roofing', 'roof repair', 'roof replacement', 'roofer', 'shingles', 'roof leak', 'new roof', 'roof inspection'],
        'google_terms': ['roofing company', 'roofer', 'roof repair'],
        'subs': ['Roof Repair', 'Roof Replacement', 'Flat Roof', 'Metal Roof', 'Roof Inspection'],
    },
    {
        'name': 'Painting',
        'group': 'construction',
        'icon': 'bi-paint-bucket',
        'craigslist_section': 'services',
        'keywords': ['painting', 'painter', 'interior painting', 'exterior painting', 'house painting', 'paint job', 'staining'],
        'google_terms': ['painting company', 'house painter', 'painting contractor'],
        'subs': ['Interior Painting', 'Exterior Painting', 'Cabinet Painting', 'Staining', 'Commercial Painting'],
    },
    {
        'name': 'Flooring',
        'group': 'construction',
        'icon': 'bi-grid-3x3',
        'craigslist_section': 'services',
        'keywords': ['flooring', 'floor installation', 'hardwood floor', 'laminate', 'vinyl flooring', 'tile floor', 'carpet installation'],
        'google_terms': ['flooring company', 'floor installation'],
        'subs': ['Hardwood', 'Laminate', 'Vinyl/LVP', 'Tile', 'Carpet Installation', 'Floor Refinishing'],
    },
    {
        'name': 'Drywall',
        'group': 'construction',
        'icon': 'bi-square',
        'craigslist_section': 'services',
        'keywords': ['drywall', 'sheetrock', 'drywall repair', 'drywall installation', 'plastering', 'wall repair'],
        'google_terms': ['drywall contractor', 'drywall repair'],
        'subs': ['Drywall Installation', 'Drywall Repair', 'Texturing', 'Plastering'],
    },
    {
        'name': 'Tile',
        'group': 'construction',
        'icon': 'bi-grid',
        'craigslist_section': 'services',
        'keywords': ['tile', 'tile installation', 'tile work', 'backsplash', 'floor tile', 'bathroom tile', 'shower tile'],
        'google_terms': ['tile installer', 'tile contractor'],
        'subs': ['Floor Tile', 'Bathroom Tile', 'Kitchen Backsplash', 'Shower Tile', 'Mosaic'],
    },
    {
        'name': 'Kitchen Remodeling',
        'group': 'construction',
        'icon': 'bi-cup-hot',
        'craigslist_section': 'services',
        'keywords': ['kitchen remodel', 'kitchen renovation', 'kitchen cabinets', 'countertop', 'kitchen design', 'kitchen update'],
        'google_terms': ['kitchen remodeling', 'kitchen renovation contractor'],
        'subs': ['Full Kitchen Remodel', 'Cabinet Refacing', 'Countertop Installation', 'Kitchen Island'],
    },
    {
        'name': 'Bathroom Remodeling',
        'group': 'construction',
        'icon': 'bi-droplet-half',
        'craigslist_section': 'services',
        'keywords': ['bathroom remodel', 'bathroom renovation', 'shower remodel', 'bathtub', 'bathroom design', 'bathroom update'],
        'google_terms': ['bathroom remodeling', 'bathroom renovation contractor'],
        'subs': ['Full Bathroom Remodel', 'Shower Conversion', 'Vanity Installation', 'Tub-to-Shower'],
    },
    {
        'name': 'Basement Finishing',
        'group': 'construction',
        'icon': 'bi-layers',
        'craigslist_section': 'services',
        'keywords': ['basement finishing', 'basement remodel', 'basement renovation', 'finished basement', 'basement waterproofing'],
        'google_terms': ['basement finishing contractor', 'basement remodeling'],
        'subs': ['Basement Finishing', 'Basement Waterproofing', 'Egress Window', 'Basement Bathroom'],
    },
    {
        'name': 'Siding',
        'group': 'construction',
        'icon': 'bi-border-all',
        'craigslist_section': 'services',
        'keywords': ['siding', 'siding installation', 'vinyl siding', 'siding repair', 'fiber cement', 'hardie board'],
        'google_terms': ['siding contractor', 'siding installation'],
        'subs': ['Vinyl Siding', 'Fiber Cement', 'Wood Siding', 'Siding Repair'],
    },
    {
        'name': 'Windows & Doors',
        'group': 'construction',
        'icon': 'bi-door-open',
        'craigslist_section': 'services',
        'keywords': ['window installation', 'door installation', 'replacement windows', 'new windows', 'entry door', 'sliding door', 'window replacement'],
        'google_terms': ['window installation', 'door installation company'],
        'subs': ['Window Replacement', 'Door Installation', 'Storm Doors', 'Patio Doors', 'Skylights'],
    },
    {
        'name': 'Moving',
        'group': 'construction',
        'icon': 'bi-truck',
        'craigslist_section': 'services',
        'keywords': ['moving', 'movers', 'moving company', 'relocation', 'packing', 'moving help', 'furniture moving'],
        'google_terms': ['moving company', 'movers near me'],
        'subs': ['Local Moving', 'Long Distance Moving', 'Packing Services', 'Piano Moving', 'Office Moving'],
    },

    # ── Automotive ─────────────────────────────────────────────
    {
        'name': 'Auto Repair',
        'group': 'auto',
        'icon': 'bi-car-front',
        'craigslist_section': 'services',
        'keywords': ['auto repair', 'car repair', 'mechanic', 'auto mechanic', 'brake repair', 'engine repair', 'transmission'],
        'google_terms': ['auto repair shop', 'car mechanic'],
        'subs': ['Engine Repair', 'Brake Service', 'Transmission', 'Diagnostics', 'Oil Change'],
    },
    {
        'name': 'Auto Body',
        'group': 'auto',
        'icon': 'bi-car-front-fill',
        'craigslist_section': 'services',
        'keywords': ['auto body', 'body shop', 'collision repair', 'dent repair', 'paint job', 'fender repair'],
        'google_terms': ['auto body shop', 'collision repair'],
        'subs': ['Collision Repair', 'Dent Repair', 'Auto Painting', 'Frame Repair'],
    },
    {
        'name': 'Towing',
        'group': 'auto',
        'icon': 'bi-truck-front',
        'craigslist_section': 'services',
        'keywords': ['towing', 'tow truck', 'roadside assistance', 'car towing', 'flatbed tow'],
        'google_terms': ['towing service', 'tow truck'],
        'subs': ['Emergency Towing', 'Long Distance Towing', 'Flatbed Towing', 'Roadside Assistance'],
    },
    {
        'name': 'Auto Detailing',
        'group': 'auto',
        'icon': 'bi-stars',
        'craigslist_section': 'services',
        'keywords': ['auto detailing', 'car detailing', 'car wash', 'paint correction', 'ceramic coating', 'interior detailing'],
        'google_terms': ['auto detailing', 'car detailing service'],
        'subs': ['Interior Detailing', 'Exterior Detailing', 'Ceramic Coating', 'Paint Correction'],
    },
    {
        'name': 'Windshield Repair',
        'group': 'auto',
        'icon': 'bi-shield-shaded',
        'craigslist_section': 'services',
        'keywords': ['windshield repair', 'windshield replacement', 'auto glass', 'cracked windshield', 'chip repair'],
        'google_terms': ['windshield repair', 'auto glass replacement'],
        'subs': ['Chip Repair', 'Windshield Replacement', 'Side Window', 'Rear Window'],
    },
    {
        'name': 'Mobile Mechanic',
        'group': 'auto',
        'icon': 'bi-tools',
        'craigslist_section': 'services',
        'keywords': ['mobile mechanic', 'mobile auto repair', 'on-site mechanic', 'mobile car repair'],
        'google_terms': ['mobile mechanic', 'mobile auto repair'],
        'subs': ['Mobile Oil Change', 'Mobile Brake Service', 'Mobile Diagnostics', 'Mobile Battery Service'],
    },

    # ── Professional Services ──────────────────────────────────
    {
        'name': 'Insurance Agent',
        'group': 'professional',
        'icon': 'bi-shield-check',
        'craigslist_section': 'services',
        'keywords': ['insurance agent', 'insurance broker', 'home insurance', 'auto insurance', 'life insurance', 'insurance quote', 'insurance policy'],
        'google_terms': ['insurance agent', 'insurance broker near me'],
        'subs': ['Home Insurance', 'Auto Insurance', 'Life Insurance', 'Business Insurance', 'Health Insurance'],
    },
    {
        'name': 'Lawyer / Attorney',
        'group': 'professional',
        'icon': 'bi-briefcase-fill',
        'craigslist_section': 'services',
        'keywords': ['lawyer', 'attorney', 'legal help', 'law firm', 'legal advice', 'legal counsel', 'litigation'],
        'google_terms': ['lawyer near me', 'attorney', 'law firm'],
        'subs': ['Personal Injury', 'Family Law', 'Real Estate Law', 'Business Law', 'Estate Planning', 'Criminal Defense', 'Immigration'],
    },
    {
        'name': 'Financial Advisor',
        'group': 'professional',
        'icon': 'bi-graph-up-arrow',
        'craigslist_section': 'services',
        'keywords': ['financial advisor', 'financial planner', 'wealth management', 'investment advisor', 'retirement planning', 'financial planning'],
        'google_terms': ['financial advisor', 'financial planner near me'],
        'subs': ['Retirement Planning', 'Investment Management', 'Tax Planning', 'Estate Planning', 'College Savings'],
    },
    {
        'name': 'Accountant / CPA',
        'group': 'professional',
        'icon': 'bi-calculator',
        'craigslist_section': 'services',
        'keywords': ['accountant', 'cpa', 'tax preparation', 'bookkeeper', 'bookkeeping', 'tax filing', 'accounting', 'tax return'],
        'google_terms': ['accountant near me', 'cpa', 'tax preparation service'],
        'subs': ['Tax Preparation', 'Bookkeeping', 'Payroll Services', 'Business Accounting', 'Tax Planning'],
    },
    {
        'name': 'Real Estate Agent',
        'group': 'professional',
        'icon': 'bi-house-door',
        'craigslist_section': 'services',
        'keywords': ['real estate agent', 'realtor', 'real estate broker', 'home buying', 'home selling', 'listing agent', 'buyers agent'],
        'google_terms': ['real estate agent near me', 'realtor'],
        'subs': ['Buyer Representation', 'Seller Representation', 'Commercial Real Estate', 'Property Management'],
    },
    {
        'name': 'Notary Public',
        'group': 'professional',
        'icon': 'bi-pen',
        'craigslist_section': 'services',
        'keywords': ['notary', 'notary public', 'mobile notary', 'notarize', 'notary services', 'loan signing agent'],
        'google_terms': ['notary near me', 'mobile notary service'],
        'subs': ['Mobile Notary', 'Loan Signing', 'Document Notarization'],
    },

    # ── Healthcare & Wellness ──────────────────────────────────
    {
        'name': 'Dentist',
        'group': 'healthcare',
        'icon': 'bi-emoji-smile',
        'craigslist_section': 'services',
        'keywords': ['dentist', 'dental', 'teeth cleaning', 'tooth pain', 'dental implant', 'braces', 'orthodontist', 'dental crown'],
        'google_terms': ['dentist near me', 'dental office', 'family dentist'],
        'subs': ['General Dentistry', 'Cosmetic Dentistry', 'Orthodontics', 'Oral Surgery', 'Pediatric Dentistry', 'Emergency Dental'],
    },
    {
        'name': 'Chiropractor',
        'group': 'healthcare',
        'icon': 'bi-person-arms-up',
        'craigslist_section': 'services',
        'keywords': ['chiropractor', 'chiropractic', 'back pain', 'spine adjustment', 'neck pain', 'spinal adjustment', 'chiropractic care'],
        'google_terms': ['chiropractor near me', 'chiropractic office'],
        'subs': ['Spinal Adjustment', 'Sports Chiropractic', 'Pediatric Chiropractic', 'Pain Management'],
    },
    {
        'name': 'Physical Therapy',
        'group': 'healthcare',
        'icon': 'bi-heart-pulse',
        'craigslist_section': 'services',
        'keywords': ['physical therapy', 'physical therapist', 'pt', 'rehab', 'rehabilitation', 'sports therapy', 'occupational therapy'],
        'google_terms': ['physical therapy near me', 'physical therapist'],
        'subs': ['Orthopedic PT', 'Sports Rehabilitation', 'Post-Surgery Rehab', 'Pediatric PT', 'Geriatric PT'],
    },
    {
        'name': 'Therapist / Counselor',
        'group': 'healthcare',
        'icon': 'bi-chat-heart',
        'craigslist_section': 'services',
        'keywords': ['therapist', 'counselor', 'therapy', 'counseling', 'psychologist', 'mental health', 'marriage counselor', 'family therapy'],
        'google_terms': ['therapist near me', 'counselor', 'mental health therapist'],
        'subs': ['Individual Therapy', 'Couples Counseling', 'Family Therapy', 'Child Therapy', 'Addiction Counseling'],
    },
    {
        'name': 'Veterinarian',
        'group': 'healthcare',
        'icon': 'bi-heart-fill',
        'craigslist_section': 'services',
        'keywords': ['veterinarian', 'vet', 'animal hospital', 'pet doctor', 'vet clinic', 'animal clinic', 'pet health'],
        'google_terms': ['veterinarian near me', 'vet clinic', 'animal hospital'],
        'subs': ['Wellness Exams', 'Vaccinations', 'Surgery', 'Dental Care', 'Emergency Vet'],
    },
    {
        'name': 'Optometrist',
        'group': 'healthcare',
        'icon': 'bi-eyeglasses',
        'craigslist_section': 'services',
        'keywords': ['optometrist', 'eye doctor', 'eye exam', 'glasses', 'contacts', 'vision', 'optician', 'eye care'],
        'google_terms': ['optometrist near me', 'eye doctor', 'eye exam'],
        'subs': ['Eye Exams', 'Contact Lenses', 'Glasses Fitting', 'Pediatric Eye Care'],
    },
    {
        'name': 'Home Health Aide',
        'group': 'healthcare',
        'icon': 'bi-person-heart',
        'craigslist_section': 'services',
        'keywords': ['home health aide', 'home health care', 'in-home care', 'caregiver', 'home nursing', 'medical home care'],
        'google_terms': ['home health aide', 'home health care service'],
        'subs': ['Skilled Nursing', 'Personal Care', 'Medication Management', 'Post-Hospital Care'],
    },
    {
        'name': 'Massage Therapist',
        'group': 'healthcare',
        'icon': 'bi-hand-index-thumb',
        'craigslist_section': 'services',
        'keywords': ['massage therapist', 'massage', 'deep tissue massage', 'sports massage', 'swedish massage', 'therapeutic massage'],
        'google_terms': ['massage therapist near me', 'massage therapy'],
        'subs': ['Deep Tissue', 'Swedish Massage', 'Sports Massage', 'Prenatal Massage', 'Hot Stone'],
    },

    # ── Events & Entertainment ─────────────────────────────────
    {
        'name': 'Photographer',
        'group': 'events',
        'icon': 'bi-camera',
        'craigslist_section': 'services',
        'keywords': ['photographer', 'photography', 'wedding photographer', 'portrait photographer', 'event photographer', 'photo shoot'],
        'google_terms': ['photographer near me', 'wedding photographer'],
        'subs': ['Wedding Photography', 'Portrait Photography', 'Event Photography', 'Real Estate Photography', 'Headshots'],
    },
    {
        'name': 'DJ / Entertainment',
        'group': 'events',
        'icon': 'bi-music-note-beamed',
        'craigslist_section': 'services',
        'keywords': ['dj', 'disc jockey', 'wedding dj', 'party dj', 'event dj', 'mobile dj', 'entertainment'],
        'google_terms': ['dj near me', 'wedding dj', 'event dj'],
        'subs': ['Wedding DJ', 'Corporate Events', 'Party DJ', 'Karaoke', 'MC Services'],
    },
    {
        'name': 'Caterer',
        'group': 'events',
        'icon': 'bi-cup-straw',
        'craigslist_section': 'services',
        'keywords': ['catering', 'caterer', 'event catering', 'wedding catering', 'corporate catering', 'food service', 'party catering'],
        'google_terms': ['caterer near me', 'catering service', 'wedding catering'],
        'subs': ['Wedding Catering', 'Corporate Catering', 'Private Events', 'Buffet Service', 'Drop-Off Catering'],
    },
    {
        'name': 'Florist',
        'group': 'events',
        'icon': 'bi-flower2',
        'craigslist_section': 'services',
        'keywords': ['florist', 'flower shop', 'flower delivery', 'wedding flowers', 'floral arrangement', 'bouquet'],
        'google_terms': ['florist near me', 'flower delivery', 'wedding florist'],
        'subs': ['Wedding Flowers', 'Event Arrangements', 'Sympathy Flowers', 'Everyday Bouquets'],
    },
    {
        'name': 'Event Planner',
        'group': 'events',
        'icon': 'bi-calendar-event',
        'craigslist_section': 'services',
        'keywords': ['event planner', 'wedding planner', 'party planner', 'event coordinator', 'event planning', 'wedding coordinator'],
        'google_terms': ['event planner near me', 'wedding planner'],
        'subs': ['Wedding Planning', 'Corporate Events', 'Birthday Parties', 'Anniversary Events', 'Fundraisers'],
    },
    {
        'name': 'Videographer',
        'group': 'events',
        'icon': 'bi-camera-video',
        'craigslist_section': 'services',
        'keywords': ['videographer', 'video production', 'wedding video', 'event video', 'promotional video', 'drone video'],
        'google_terms': ['videographer near me', 'wedding videographer'],
        'subs': ['Wedding Video', 'Corporate Video', 'Promotional Video', 'Drone Footage', 'Live Streaming'],
    },

    # ── Education & Training ───────────────────────────────────
    {
        'name': 'Tutor',
        'group': 'education',
        'icon': 'bi-book',
        'craigslist_section': 'services',
        'keywords': ['tutor', 'tutoring', 'math tutor', 'reading tutor', 'test prep', 'sat prep', 'homework help', 'academic tutor'],
        'google_terms': ['tutor near me', 'tutoring service'],
        'subs': ['Math Tutoring', 'Reading/Writing', 'SAT/ACT Prep', 'Science Tutoring', 'ESL/Language'],
    },
    {
        'name': 'Music Teacher',
        'group': 'education',
        'icon': 'bi-music-note',
        'craigslist_section': 'services',
        'keywords': ['music teacher', 'music lessons', 'piano lessons', 'guitar lessons', 'voice lessons', 'music instructor', 'singing lessons'],
        'google_terms': ['music lessons near me', 'piano teacher', 'guitar lessons'],
        'subs': ['Piano Lessons', 'Guitar Lessons', 'Voice Lessons', 'Drum Lessons', 'Violin Lessons'],
    },
    {
        'name': 'Driving Instructor',
        'group': 'education',
        'icon': 'bi-stoplights',
        'craigslist_section': 'services',
        'keywords': ['driving instructor', 'driving lessons', 'driving school', 'learn to drive', 'drivers ed', 'driving teacher'],
        'google_terms': ['driving school near me', 'driving lessons', 'driving instructor'],
        'subs': ['Teen Driver Education', 'Adult Driving Lessons', 'Defensive Driving', 'Commercial License'],
    },
    {
        'name': 'Personal Trainer',
        'group': 'education',
        'icon': 'bi-person-walking',
        'craigslist_section': 'services',
        'keywords': ['personal trainer', 'fitness trainer', 'personal training', 'fitness coach', 'gym trainer', 'workout trainer'],
        'google_terms': ['personal trainer near me', 'fitness trainer'],
        'subs': ['One-on-One Training', 'Group Fitness', 'Weight Loss', 'Strength Training', 'Online Training'],
    },
    {
        'name': 'Martial Arts Instructor',
        'group': 'education',
        'icon': 'bi-trophy',
        'craigslist_section': 'services',
        'keywords': ['martial arts', 'karate', 'taekwondo', 'jiu jitsu', 'boxing', 'self defense', 'mma', 'kung fu'],
        'google_terms': ['martial arts classes near me', 'karate school'],
        'subs': ['Karate', 'Taekwondo', 'Brazilian Jiu Jitsu', 'Boxing', 'Self Defense'],
    },

    # ── Pet Services ───────────────────────────────────────────
    {
        'name': 'Pet Groomer',
        'group': 'pet',
        'icon': 'bi-scissors',
        'craigslist_section': 'services',
        'keywords': ['pet groomer', 'dog grooming', 'cat grooming', 'pet grooming', 'mobile groomer', 'dog bath', 'pet haircut'],
        'google_terms': ['pet groomer near me', 'dog grooming'],
        'subs': ['Dog Grooming', 'Cat Grooming', 'Mobile Grooming', 'Nail Trimming', 'De-Shedding'],
    },
    {
        'name': 'Dog Walker',
        'group': 'pet',
        'icon': 'bi-signpost-split',
        'craigslist_section': 'services',
        'keywords': ['dog walker', 'dog walking', 'pet walking', 'dog walk service', 'daily dog walk'],
        'google_terms': ['dog walker near me', 'dog walking service'],
        'subs': ['Daily Walks', 'Group Walks', 'Puppy Walks', 'Senior Dog Walks'],
    },
    {
        'name': 'Pet Sitter',
        'group': 'pet',
        'icon': 'bi-house-heart-fill',
        'craigslist_section': 'services',
        'keywords': ['pet sitter', 'pet sitting', 'dog sitter', 'cat sitter', 'house sitting', 'overnight pet care'],
        'google_terms': ['pet sitter near me', 'pet sitting service'],
        'subs': ['In-Home Pet Sitting', 'Overnight Care', 'Drop-In Visits', 'Cat Sitting'],
    },
    {
        'name': 'Dog Trainer',
        'group': 'pet',
        'icon': 'bi-clipboard-check',
        'craigslist_section': 'services',
        'keywords': ['dog trainer', 'dog training', 'puppy training', 'obedience training', 'behavior training', 'dog obedience'],
        'google_terms': ['dog trainer near me', 'dog training'],
        'subs': ['Puppy Training', 'Obedience Training', 'Behavior Modification', 'Board & Train', 'Group Classes'],
    },
    {
        'name': 'Pet Boarding',
        'group': 'pet',
        'icon': 'bi-building-check',
        'craigslist_section': 'services',
        'keywords': ['pet boarding', 'dog boarding', 'kennel', 'dog kennel', 'cat boarding', 'pet hotel', 'doggy daycare'],
        'google_terms': ['pet boarding near me', 'dog boarding', 'doggy daycare'],
        'subs': ['Dog Boarding', 'Cat Boarding', 'Doggy Daycare', 'Luxury Pet Hotel'],
    },

    # ── Senior Care ────────────────────────────────────────────
    {
        'name': 'Companion Care',
        'group': 'senior',
        'icon': 'bi-people-fill',
        'craigslist_section': 'services',
        'keywords': ['companion care', 'senior companion', 'elderly care', 'senior care', 'elder care', 'senior assistance', 'aging in place'],
        'google_terms': ['companion care near me', 'senior companion service'],
        'subs': ['Daily Companionship', 'Errand Assistance', 'Meal Preparation', 'Light Housekeeping', 'Transportation'],
    },
    {
        'name': 'Senior Home Modification',
        'group': 'senior',
        'icon': 'bi-house-gear-fill',
        'craigslist_section': 'services',
        'keywords': ['senior home modification', 'aging in place', 'grab bars', 'wheelchair ramp', 'stair lift', 'accessibility', 'ada modification'],
        'google_terms': ['senior home modification', 'aging in place contractor'],
        'subs': ['Grab Bar Installation', 'Wheelchair Ramp', 'Stair Lift', 'Walk-In Tub', 'Accessibility Remodel'],
    },
    {
        'name': 'Medical Alert Systems',
        'group': 'senior',
        'icon': 'bi-bell',
        'craigslist_section': 'services',
        'keywords': ['medical alert', 'life alert', 'personal emergency response', 'fall detection', 'medical alarm', 'senior alert system'],
        'google_terms': ['medical alert system', 'personal emergency response'],
        'subs': ['In-Home Systems', 'Mobile Systems', 'Fall Detection', 'GPS Tracking'],
    },

    # ── Technology ─────────────────────────────────────────────
    {
        'name': 'IT Support',
        'group': 'technology',
        'icon': 'bi-headset',
        'craigslist_section': 'services',
        'keywords': ['it support', 'tech support', 'computer help', 'network support', 'it services', 'helpdesk', 'it consulting'],
        'google_terms': ['it support near me', 'tech support service'],
        'subs': ['Business IT Support', 'Network Setup', 'Server Management', 'Cloud Services', 'Cybersecurity'],
    },
    {
        'name': 'Computer Repair',
        'group': 'technology',
        'icon': 'bi-pc-display',
        'craigslist_section': 'services',
        'keywords': ['computer repair', 'pc repair', 'laptop repair', 'computer fix', 'virus removal', 'data recovery', 'screen repair'],
        'google_terms': ['computer repair near me', 'laptop repair'],
        'subs': ['Desktop Repair', 'Laptop Repair', 'Virus Removal', 'Data Recovery', 'Hardware Upgrade'],
    },
    {
        'name': 'Managed IT Services',
        'group': 'technology',
        'icon': 'bi-hdd-network',
        'craigslist_section': 'services',
        'keywords': ['managed it', 'managed services', 'msp', 'managed service provider', 'it management', 'outsourced it'],
        'google_terms': ['managed it services', 'managed service provider near me'],
        'subs': ['Network Monitoring', 'Backup & Recovery', 'Help Desk', 'Cloud Management', 'IT Strategy'],
    },
    {
        'name': 'Web Design',
        'group': 'technology',
        'icon': 'bi-code-slash',
        'craigslist_section': 'services',
        'keywords': ['web design', 'website design', 'web developer', 'website builder', 'web development', 'wordpress'],
        'google_terms': ['web design near me', 'website designer'],
        'subs': ['Business Websites', 'E-commerce', 'WordPress', 'Website Redesign', 'SEO'],
    },
    {
        'name': 'Phone / Tablet Repair',
        'group': 'technology',
        'icon': 'bi-phone',
        'craigslist_section': 'services',
        'keywords': ['phone repair', 'iphone repair', 'screen repair', 'tablet repair', 'cell phone repair', 'cracked screen', 'samsung repair'],
        'google_terms': ['phone repair near me', 'cell phone repair'],
        'subs': ['Screen Replacement', 'Battery Replacement', 'Water Damage', 'Charging Port Repair'],
    },
]


class Command(BaseCommand):
    help = 'Seed service categories and subcategories'

    def handle(self, *args, **options):
        created_count = 0
        for i, cat_data in enumerate(CATEGORIES):
            cat, created = ServiceCategory.objects.update_or_create(
                slug=slugify(cat_data['name']),
                defaults={
                    'name': cat_data['name'],
                    'icon': cat_data.get('icon', ''),
                    'industry_group': cat_data.get('group', 'home_services'),
                    'craigslist_section': cat_data.get('craigslist_section', ''),
                    'default_keywords': cat_data.get('keywords', []),
                    'google_maps_terms': cat_data.get('google_terms', []),
                    'sort_order': i,
                    'is_active': True,
                }
            )
            if created:
                created_count += 1

            for sub_name in cat_data.get('subs', []):
                ServiceSubcategory.objects.update_or_create(
                    category=cat,
                    slug=slugify(sub_name),
                    defaults={'name': sub_name}
                )

        total = ServiceCategory.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created_count} new categories (total: {total}) with subcategories'
        ))
