from django.shortcuts import render, get_object_or_404
from django.http import Http404


INDUSTRIES = {
    'commercial-cleaning': {
        'slug': 'commercial-cleaning',
        'name': 'Commercial Cleaning',
        'icon': 'bi-stars',
        'color': '#0D9488',
        'headline': 'Find Every Business That Needs Cleaning — Before They Search Google',
        'stat_line': '1,409 restaurants in NYC received health violations this month. Each one needs a cleaning service.',
        'description': 'SalesSignal AI monitors health inspections, new business filings, property sales, and community requests to deliver cleaning leads before your competitors even know they exist.',
        'leads': [
            {
                'pill': 'Health', 'pill_color': 'purple', 'pill_icon': 'bi-clipboard2-pulse',
                'urgency': 'hot',
                'title': 'Health Inspection Violation — Score 38',
                'detail1': 'Restaurant: <span class="redacted-blur">Jade Palace Kitchen</span> · 94 Mott St, Manhattan NY',
                'detail2': 'Filth flies, grease buildup on walls and floors, improper food storage temps. Needs deep cleaning, pest control.',
                'time': '8 min ago',
            },
            {
                'pill': 'Filing', 'pill_color': 'blue', 'pill_icon': 'bi-building',
                'urgency': 'warm',
                'title': 'New Liquor License Application — Bar & Grill',
                'detail1': 'Business: <span class="redacted-blur">Sunset Social House LLC</span> · Williamsburg, Brooklyn NY',
                'detail2': 'New restaurant opening. Needs pre-opening deep clean, regular maintenance contract, window cleaning.',
                'time': '45 min ago',
            },
            {
                'pill': 'Permit', 'pill_color': 'amber', 'pill_icon': 'bi-file-earmark-check',
                'urgency': 'warm',
                'title': 'New Certificate of Occupancy — Commercial Space',
                'detail1': 'Address: 218 W 14th St, Manhattan NY 10011',
                'detail2': 'New commercial tenant moving in. Post-construction cleaning, regular janitorial service opportunity.',
                'time': '2 hr ago',
            },
            {
                'pill': 'Sale', 'pill_color': 'amber', 'pill_icon': 'bi-house-door-fill',
                'urgency': 'warm',
                'title': 'Property Sold — $1,250,000',
                'detail1': 'Buyer: <span class="redacted-blur">R. & M. Patterson</span> · 67 Prospect Park West, Brooklyn NY',
                'detail2': 'New homeowner. Move-in deep cleaning, window washing, carpet cleaning opportunity.',
                'time': '3 hr ago',
            },
        ],
        'sources': [
            {'name': 'NYC Health Inspections', 'icon': 'bi-clipboard2-pulse', 'desc': 'Every restaurant violation with scores, addresses, and violation details'},
            {'name': 'Business Filings (DOS)', 'icon': 'bi-building', 'desc': 'New LLC and corporation filings — restaurants, offices, retail'},
            {'name': 'ACRIS Property Sales', 'icon': 'bi-house-door', 'desc': 'Every property sale triggers move-in cleaning demand'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': '"Looking for a cleaning service" posts detected across 15+ platforms'},
        ],
    },
    'plumbing': {
        'slug': 'plumbing',
        'name': 'Plumbing',
        'icon': 'bi-droplet-fill',
        'color': '#3B82F6',
        'headline': 'Every Permit, Every Violation, Every Homeowner Request — In Your Inbox',
        'stat_line': 'NYC issues 200+ plumbing permits per week. Each one is a job your competitor might get first.',
        'description': 'SalesSignal AI monitors DOB permits, building violations, community forums, and property sales to find people who need a plumber right now.',
        'leads': [
            {
                'pill': 'Permit', 'pill_color': 'amber', 'pill_icon': 'bi-file-earmark-check',
                'urgency': 'warm',
                'title': 'DOB Plumbing Permit Filed — Residential',
                'detail1': 'Address: 1422 Ocean Ave, Flatbush, Brooklyn NY',
                'detail2': 'Plumbing alteration permit. Homeowner may need additional plumbing work, fixtures, water heater.',
                'time': '22 min ago',
            },
            {
                'pill': 'Violation', 'pill_color': 'coral', 'pill_icon': 'bi-exclamation-triangle-fill',
                'urgency': 'hot',
                'title': 'DOB Violation — Defective Plumbing',
                'detail1': 'Owner: <span class="redacted-blur">S. Petrov</span> · 89-12 Elmhurst Ave, Queens NY',
                'detail2': 'Leaking pipes causing water damage to adjacent unit. Must cure within 30 days. $5,000 penalty.',
                'time': '1 hr ago',
            },
            {
                'pill': 'Nextdoor', 'pill_color': 'green', 'pill_icon': 'bi-people-fill',
                'urgency': 'hot',
                'title': '"Need an emergency plumber — pipe burst"',
                'detail1': 'Author: <span class="redacted-blur">Lisa M.</span> · Carroll Gardens, Brooklyn NY',
                'detail2': 'Pipe burst under kitchen sink. Water everywhere. Need someone who can come today.',
                'time': '4 min ago',
            },
            {
                'pill': 'Sale', 'pill_color': 'amber', 'pill_icon': 'bi-house-door-fill',
                'urgency': 'warm',
                'title': 'Property Sold — $625,000',
                'detail1': 'Buyer: <span class="redacted-blur">T. & A. Nguyen</span> · Astoria, Queens NY',
                'detail2': 'New homeowner. Older building — likely needs plumbing inspection, fixture updates, water heater check.',
                'time': '5 hr ago',
            },
        ],
        'sources': [
            {'name': 'NYC DOB Permits', 'icon': 'bi-file-earmark-check', 'desc': 'Plumbing permits filed daily — alteration, new install, emergency'},
            {'name': 'DOB Violations', 'icon': 'bi-exclamation-triangle', 'desc': 'Building violations requiring plumbing remediation'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': '"I need a plumber" posts from Nextdoor, Reddit, Facebook groups'},
            {'name': 'ACRIS Property Sales', 'icon': 'bi-house-door', 'desc': 'New homeowners who need plumbing inspections and updates'},
        ],
    },
    'electrical': {
        'slug': 'electrical',
        'name': 'Electrical',
        'icon': 'bi-lightning-fill',
        'color': '#F59E0B',
        'headline': 'Electrical Permits, Violations, and Urgent Requests — Found Automatically',
        'stat_line': 'Every new construction permit requires electrical work. We find them the day they\'re filed.',
        'description': 'SalesSignal AI monitors electrical permits, fire safety violations, new construction filings, and community requests so you\'re always first to know.',
        'leads': [
            {
                'pill': 'Permit', 'pill_color': 'amber', 'pill_icon': 'bi-file-earmark-check',
                'urgency': 'warm',
                'title': 'Electrical Permit Filed — Commercial Renovation',
                'detail1': 'Address: 550 Broadway, SoHo, Manhattan NY',
                'detail2': 'Full electrical rewiring for commercial tenant buildout. Sub-contracting opportunity.',
                'time': '35 min ago',
            },
            {
                'pill': 'Violation', 'pill_color': 'coral', 'pill_icon': 'bi-exclamation-triangle-fill',
                'urgency': 'hot',
                'title': 'Fire Safety Violation — Faulty Wiring',
                'detail1': 'Owner: <span class="redacted-blur">K. Abramov</span> · 2115 Brighton Beach Ave, Brooklyn NY',
                'detail2': 'Exposed wiring in commercial space, no GFCI in wet areas. Must remediate within 30 days.',
                'time': '1 hr ago',
            },
            {
                'pill': 'Permit', 'pill_color': 'blue', 'pill_icon': 'bi-building',
                'urgency': 'warm',
                'title': 'New Construction Permit — 12-Unit Residential',
                'detail1': 'Address: 44-20 Vernon Blvd, Long Island City, Queens NY',
                'detail2': 'New 12-unit building. Full electrical rough-in and finish work. Large contract opportunity.',
                'time': '3 hr ago',
            },
            {
                'pill': 'Community', 'pill_color': 'green', 'pill_icon': 'bi-people-fill',
                'urgency': 'hot',
                'title': '"Outlets sparking — need an electrician ASAP"',
                'detail1': 'Author: <span class="redacted-blur">Mark T.</span> · Park Slope, Brooklyn NY',
                'detail2': 'Multiple outlets sparking when plugging in appliances. Circuit breaker keeps tripping.',
                'time': '11 min ago',
            },
        ],
        'sources': [
            {'name': 'NYC DOB Permits', 'icon': 'bi-file-earmark-check', 'desc': 'Electrical permits — residential, commercial, new construction'},
            {'name': 'Fire Safety Violations', 'icon': 'bi-exclamation-triangle', 'desc': 'FDNY and DOB violations requiring electrical remediation'},
            {'name': 'New Construction Filings', 'icon': 'bi-building', 'desc': 'Every new building needs a full electrical system'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': 'Urgent electrical requests from neighborhood forums'},
        ],
    },
    'hvac': {
        'slug': 'hvac',
        'name': 'HVAC',
        'icon': 'bi-thermometer-half',
        'color': '#8B5CF6',
        'headline': 'Seasonal Demand Spikes. Year-Round Lead Flow.',
        'stat_line': 'When temperatures hit extremes, HVAC requests spike 400%. We detect every one.',
        'description': 'SalesSignal AI monitors HVAC permits, heating and cooling violations, weather alerts that trigger demand surges, and community requests for instant lead delivery.',
        'leads': [
            {
                'pill': 'Permit', 'pill_color': 'amber', 'pill_icon': 'bi-file-earmark-check',
                'urgency': 'warm',
                'title': 'HVAC Permit Filed — Boiler Replacement',
                'detail1': 'Address: 1850 Grand Concourse, Bronx NY',
                'detail2': 'Commercial boiler replacement in 40-unit building. Large installation contract.',
                'time': '1 hr ago',
            },
            {
                'pill': 'Violation', 'pill_color': 'coral', 'pill_icon': 'bi-exclamation-triangle-fill',
                'urgency': 'hot',
                'title': 'HPD Heat Violation — No Heat Complaint',
                'detail1': 'Owner: <span class="redacted-blur">D. Okafor Properties</span> · Washington Heights, Manhattan NY',
                'detail2': 'Tenants reporting no heat. Landlord must repair heating system within 24 hours or face daily fines.',
                'time': '18 min ago',
            },
            {
                'pill': 'Community', 'pill_color': 'green', 'pill_icon': 'bi-people-fill',
                'urgency': 'hot',
                'title': '"AC unit died — who\'s good and available this week?"',
                'detail1': 'Author: <span class="redacted-blur">Rachel S.</span> · Cobble Hill, Brooklyn NY',
                'detail2': 'Central AC not cooling. Thermostat reads 85°F inside. Needs diagnosis and likely replacement.',
                'time': '7 min ago',
            },
            {
                'pill': 'Weather', 'pill_color': 'coral', 'pill_icon': 'bi-cloud-sun-fill',
                'urgency': 'hot',
                'title': 'Heat Wave Alert — 5-Day 95°F+ Forecast',
                'detail1': 'Coverage: All five boroughs, NYC metro area',
                'detail2': 'Extended heat wave incoming. AC repair and installation demand about to spike. 47 related posts in last 6 hours.',
                'time': '30 min ago',
            },
        ],
        'sources': [
            {'name': 'NYC DOB Permits', 'icon': 'bi-file-earmark-check', 'desc': 'HVAC and boiler permits — installs, replacements, alterations'},
            {'name': 'HPD Violations', 'icon': 'bi-exclamation-triangle', 'desc': 'Heat and cooling violations requiring immediate HVAC work'},
            {'name': 'Weather Alerts', 'icon': 'bi-cloud-sun', 'desc': 'Extreme weather triggers demand spikes — we alert you first'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': 'AC broken, furnace out, thermostat issues — detected in real-time'},
        ],
    },
    'general-contracting': {
        'slug': 'general-contracting',
        'name': 'General Contracting',
        'icon': 'bi-hammer',
        'color': '#DC2626',
        'headline': 'New Buildings, Renovations, and Violations — Every Contractor\'s Pipeline',
        'stat_line': 'NYC filed 3,200+ construction permits last month. How many did you know about?',
        'description': 'SalesSignal AI monitors new building permits, alteration filings, DOB violations requiring remediation, and property sales where new owners need renovation work.',
        'leads': [
            {
                'pill': 'Permit', 'pill_color': 'blue', 'pill_icon': 'bi-building',
                'urgency': 'warm',
                'title': 'New Building Permit — 6-Story Mixed Use',
                'detail1': 'Address: 23-15 Jackson Ave, Long Island City, Queens NY',
                'detail2': 'New 6-story mixed-use building. Ground-floor retail, 24 residential units. GC needed.',
                'time': '2 hr ago',
            },
            {
                'pill': 'Permit', 'pill_color': 'amber', 'pill_icon': 'bi-file-earmark-check',
                'urgency': 'warm',
                'title': 'Major Alteration Permit — Gut Renovation',
                'detail1': 'Address: 412 Atlantic Ave, Boerum Hill, Brooklyn NY',
                'detail2': 'Full gut renovation of 3-story brownstone. Structural, plumbing, electrical, finishes.',
                'time': '4 hr ago',
            },
            {
                'pill': 'Violation', 'pill_color': 'coral', 'pill_icon': 'bi-exclamation-triangle-fill',
                'urgency': 'hot',
                'title': 'DOB Violation — Unsafe Facade, $25,000 Penalty',
                'detail1': 'Owner: <span class="redacted-blur">Greenpoint Holdings Corp</span> · 145 Nassau Ave, Brooklyn NY',
                'detail2': 'Crumbling facade, falling masonry. Must hire licensed contractor for remediation within 60 days.',
                'time': '45 min ago',
            },
            {
                'pill': 'Sale', 'pill_color': 'amber', 'pill_icon': 'bi-house-door-fill',
                'urgency': 'warm',
                'title': 'Property Sold — $2,100,000',
                'detail1': 'Buyer: <span class="redacted-blur">Apex Development Group</span> · 88 Wythe Ave, Williamsburg, Brooklyn NY',
                'detail2': 'Investment property. New owner likely planning renovation or conversion. GC opportunity.',
                'time': '6 hr ago',
            },
        ],
        'sources': [
            {'name': 'NYC DOB Permits', 'icon': 'bi-file-earmark-check', 'desc': 'New building, alteration, and demolition permits filed daily'},
            {'name': 'DOB Violations', 'icon': 'bi-exclamation-triangle', 'desc': 'Facade, structural, and safety violations requiring contractor remediation'},
            {'name': 'ACRIS Property Sales', 'icon': 'bi-house-door', 'desc': 'Property sales to investors and developers signal renovation projects'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': '"Need a contractor for..." posts from neighborhood forums'},
        ],
    },
    'pest-control': {
        'slug': 'pest-control',
        'name': 'Pest Control',
        'icon': 'bi-bug-fill',
        'color': '#059669',
        'headline': 'Every Restaurant Violation. Every Rodent Complaint. Every New Lead.',
        'stat_line': '68% of NYC restaurants cited for pest-related violations need a pest control service within 30 days.',
        'description': 'SalesSignal AI monitors health inspection pest violations, community pest complaints, and new restaurant openings to deliver leads that need you now.',
        'leads': [
            {
                'pill': 'Health', 'pill_color': 'purple', 'pill_icon': 'bi-clipboard2-pulse',
                'urgency': 'hot',
                'title': 'Health Violation — Evidence of Mice (Code 08A)',
                'detail1': 'Restaurant: <span class="redacted-blur">Bella Napoli Pizzeria</span> · 3rd Ave, Bay Ridge, Brooklyn NY',
                'detail2': 'Mouse droppings found in dry storage and prep area. Must remediate before re-inspection in 14 days.',
                'time': '15 min ago',
            },
            {
                'pill': 'Health', 'pill_color': 'coral', 'pill_icon': 'bi-clipboard2-pulse',
                'urgency': 'hot',
                'title': 'Health Violation — Roach Activity (Code 08A)',
                'detail1': 'Restaurant: <span class="redacted-blur">Tasty Wok Express</span> · Canal St, Manhattan NY',
                'detail2': 'Live roaches observed near dishwashing area. Score: 44. Needs immediate pest treatment.',
                'time': '38 min ago',
            },
            {
                'pill': 'Community', 'pill_color': 'green', 'pill_icon': 'bi-people-fill',
                'urgency': 'hot',
                'title': '"Mice in our apartment — landlord won\'t help"',
                'detail1': 'Author: <span class="redacted-blur">Jennifer K.</span> · Bushwick, Brooklyn NY',
                'detail2': 'Seeing mice in kitchen nightly. Landlord unresponsive. Looking for affordable pest control.',
                'time': '22 min ago',
            },
            {
                'pill': 'Filing', 'pill_color': 'blue', 'pill_icon': 'bi-building',
                'urgency': 'warm',
                'title': 'New Restaurant Filing — Fast Casual Concept',
                'detail1': 'Business: <span class="redacted-blur">Fresh Bowl Co. LLC</span> · East Village, Manhattan NY',
                'detail2': 'New restaurant opening. Needs initial pest treatment, ongoing prevention contract.',
                'time': '3 hr ago',
            },
        ],
        'sources': [
            {'name': 'NYC Health Inspections', 'icon': 'bi-clipboard2-pulse', 'desc': 'Pest-related violation codes (04L, 08A, 08B, 08C) with addresses'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': 'Pest complaints from Nextdoor, Reddit, and neighborhood groups'},
            {'name': 'Business Filings', 'icon': 'bi-building', 'desc': 'New restaurant filings — every one needs a pest control contract'},
            {'name': 'HPD Complaints', 'icon': 'bi-exclamation-triangle', 'desc': 'Residential pest complaints filed with the city'},
        ],
    },
    'landscaping': {
        'slug': 'landscaping',
        'name': 'Landscaping',
        'icon': 'bi-tree-fill',
        'color': '#10B981',
        'headline': 'New Homeowners, New Construction, Seasonal Demand — Captured',
        'stat_line': 'Every property sale is a landscaping lead. NYC averages 1,200+ residential sales per month.',
        'description': 'SalesSignal AI monitors property sales, new building certificates, community requests, and seasonal weather patterns to deliver landscaping leads year-round.',
        'leads': [
            {
                'pill': 'Sale', 'pill_color': 'amber', 'pill_icon': 'bi-house-door-fill',
                'urgency': 'warm',
                'title': 'Property Sold — $890,000',
                'detail1': 'Buyer: <span class="redacted-blur">M. & K. Henderson</span> · Ditmas Park, Brooklyn NY',
                'detail2': 'Victorian home with large yard. New owner likely needs lawn care, garden cleanup, tree trimming.',
                'time': '2 hr ago',
            },
            {
                'pill': 'Permit', 'pill_color': 'blue', 'pill_icon': 'bi-building',
                'urgency': 'warm',
                'title': 'Certificate of Occupancy — New Townhouse Development',
                'detail1': 'Address: 180 Bainbridge St, Bed-Stuy, Brooklyn NY',
                'detail2': 'New 4-unit townhouse development completed. Needs full landscaping — lawn, plantings, hardscaping.',
                'time': '5 hr ago',
            },
            {
                'pill': 'Community', 'pill_color': 'green', 'pill_icon': 'bi-people-fill',
                'urgency': 'hot',
                'title': '"Backyard is a jungle — need a landscaper"',
                'detail1': 'Author: <span class="redacted-blur">Tom W.</span> · Bayside, Queens NY',
                'detail2': 'Overgrown backyard, dead trees, broken fence. Looking for full cleanup and weekly maintenance.',
                'time': '19 min ago',
            },
            {
                'pill': 'Weather', 'pill_color': 'green', 'pill_icon': 'bi-cloud-sun-fill',
                'urgency': 'warm',
                'title': 'Spring Season Start — Demand Surge Detected',
                'detail1': 'Coverage: NYC metro, Long Island, Westchester',
                'detail2': 'First week above 60°F. Community posts about landscaping up 340% from last week.',
                'time': '1 hr ago',
            },
        ],
        'sources': [
            {'name': 'ACRIS Property Sales', 'icon': 'bi-house-door', 'desc': 'New homeowners with yards need landscaping immediately'},
            {'name': 'NYC DOB Certificates', 'icon': 'bi-building', 'desc': 'New construction completions needing initial landscaping'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': '"Need a landscaper" posts from Nextdoor, Facebook groups'},
            {'name': 'Weather Patterns', 'icon': 'bi-cloud-sun', 'desc': 'Seasonal triggers that spike landscaping demand'},
        ],
    },
    'roofing': {
        'slug': 'roofing',
        'name': 'Roofing',
        'icon': 'bi-house-fill',
        'color': '#D97706',
        'headline': 'Storm Damage, Permits, and Homeowner Requests — First To Know',
        'stat_line': 'After every major storm, roofing requests spike 600%. We detect them in real-time.',
        'description': 'SalesSignal AI monitors weather alerts, roofing permits, facade and roof violations, and community requests so you can respond before the storm clears.',
        'leads': [
            {
                'pill': 'Weather', 'pill_color': 'coral', 'pill_icon': 'bi-cloud-lightning-rain-fill',
                'urgency': 'hot',
                'title': 'Severe Storm Warning — High Winds & Hail',
                'detail1': 'Coverage: Brooklyn, Queens, Staten Island',
                'detail2': '60mph wind gusts and quarter-sized hail expected. 23 roof-related posts in last 2 hours.',
                'time': '12 min ago',
            },
            {
                'pill': 'Permit', 'pill_color': 'amber', 'pill_icon': 'bi-file-earmark-check',
                'urgency': 'warm',
                'title': 'Roofing Permit Filed — Full Replacement',
                'detail1': 'Address: 1055 E 38th St, Flatbush, Brooklyn NY',
                'detail2': 'Full roof replacement on 3-family home. Permit just filed — homeowner shopping for roofers.',
                'time': '3 hr ago',
            },
            {
                'pill': 'Violation', 'pill_color': 'coral', 'pill_icon': 'bi-exclamation-triangle-fill',
                'urgency': 'hot',
                'title': 'DOB Violation — Damaged Roof Membrane',
                'detail1': 'Owner: <span class="redacted-blur">Bay Realty Associates</span> · 4th Ave, Sunset Park, Brooklyn NY',
                'detail2': 'Water infiltration from damaged roof membrane. Must repair within 60 days or face escalating fines.',
                'time': '1 hr ago',
            },
            {
                'pill': 'Community', 'pill_color': 'green', 'pill_icon': 'bi-people-fill',
                'urgency': 'hot',
                'title': '"Roof leaking badly after last night\'s rain"',
                'detail1': 'Author: <span class="redacted-blur">Angela P.</span> · Throgs Neck, Bronx NY',
                'detail2': 'Ceiling stains, water dripping into top floor. Needs emergency tarp and full roof assessment.',
                'time': '25 min ago',
            },
        ],
        'sources': [
            {'name': 'Weather Alerts', 'icon': 'bi-cloud-lightning-rain', 'desc': 'Storms, hail, and high winds trigger immediate roofing demand'},
            {'name': 'NYC DOB Permits', 'icon': 'bi-file-earmark-check', 'desc': 'Roofing permits — replacements, repairs, new construction'},
            {'name': 'DOB Violations', 'icon': 'bi-exclamation-triangle', 'desc': 'Roof and facade violations requiring licensed roofing work'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': '"Roof leaking" and storm damage posts from neighborhood forums'},
        ],
    },
    'moving': {
        'slug': 'moving',
        'name': 'Moving',
        'icon': 'bi-truck',
        'color': '#6366F1',
        'headline': 'Every Property Sale Is a Moving Lead',
        'stat_line': 'NYC averages 4,000+ property transactions per month. Every one needs a mover.',
        'description': 'SalesSignal AI monitors ACRIS property sales, new certificates of occupancy, and community posts about moving to deliver leads who need movers right now.',
        'leads': [
            {
                'pill': 'Sale', 'pill_color': 'amber', 'pill_icon': 'bi-house-door-fill',
                'urgency': 'warm',
                'title': 'Property Sold — $520,000',
                'detail1': 'Buyer: <span class="redacted-blur">A. Williams</span> · 1890 Nostrand Ave, Flatbush, Brooklyn NY',
                'detail2': 'Residential purchase. Closing in 30 days — needs local mover for 2-bedroom apartment.',
                'time': '1 hr ago',
            },
            {
                'pill': 'Sale', 'pill_color': 'amber', 'pill_icon': 'bi-house-door-fill',
                'urgency': 'warm',
                'title': 'Property Sold — $1,800,000',
                'detail1': 'Buyer: <span class="redacted-blur">H. & C. Goldman</span> · 72nd St, Upper West Side, Manhattan NY',
                'detail2': 'Luxury condo purchase. Needs white-glove moving service, storage, packing.',
                'time': '3 hr ago',
            },
            {
                'pill': 'Permit', 'pill_color': 'blue', 'pill_icon': 'bi-building',
                'urgency': 'warm',
                'title': 'Certificate of Occupancy — New Condo Building',
                'detail1': 'Address: 21-30 44th Dr, Long Island City, Queens NY',
                'detail2': 'New 48-unit condo building ready for occupancy. Dozens of move-ins expected over next 60 days.',
                'time': '5 hr ago',
            },
            {
                'pill': 'Community', 'pill_color': 'green', 'pill_icon': 'bi-people-fill',
                'urgency': 'hot',
                'title': '"Moving next month — need a reliable mover"',
                'detail1': 'Author: <span class="redacted-blur">Chris D.</span> · Astoria, Queens NY',
                'detail2': 'Moving from 1BR to 3BR across borough. Has piano. Looking for insured movers with good reviews.',
                'time': '16 min ago',
            },
        ],
        'sources': [
            {'name': 'ACRIS Property Sales', 'icon': 'bi-house-door', 'desc': 'Every property sale means someone is moving in — and someone is moving out'},
            {'name': 'Certificates of Occupancy', 'icon': 'bi-building', 'desc': 'New buildings going live mean dozens of move-ins'},
            {'name': 'Community Posts', 'icon': 'bi-people-fill', 'desc': '"Need a mover" posts from Nextdoor, Reddit, Facebook groups'},
        ],
    },
    'insurance': {
        'slug': 'insurance',
        'name': 'Insurance',
        'icon': 'bi-shield-check',
        'color': '#0EA5E9',
        'headline': 'New Businesses, New Homeowners, New Policies Needed',
        'stat_line': 'Every new business filing, property sale, and liquor license application needs insurance.',
        'description': 'SalesSignal AI monitors new business filings, property sales, liquor license applications, and building permits to find people who need insurance policies right now.',
        'leads': [
            {
                'pill': 'Filing', 'pill_color': 'blue', 'pill_icon': 'bi-building',
                'urgency': 'warm',
                'title': 'New LLC — Bright Side Construction Corp.',
                'detail1': 'Filed: <strong>Kings County</strong> · Domestic Business Corporation',
                'detail2': 'New construction business. Needs general liability, workers comp, commercial auto, bonding.',
                'time': '1 hr ago',
            },
            {
                'pill': 'Sale', 'pill_color': 'amber', 'pill_icon': 'bi-house-door-fill',
                'urgency': 'warm',
                'title': 'Property Sold — $675,000',
                'detail1': 'Buyer: <span class="redacted-blur">P. & R. Santiago</span> · Woodside, Queens NY',
                'detail2': 'New homeowner. Needs homeowner\'s insurance, possibly umbrella policy. Closing in 3 weeks.',
                'time': '2 hr ago',
            },
            {
                'pill': 'License', 'pill_color': 'purple', 'pill_icon': 'bi-cup-straw',
                'urgency': 'warm',
                'title': 'Liquor License Application — New Bar',
                'detail1': 'Business: <span class="redacted-blur">The Copper Still LLC</span> · Lower East Side, Manhattan NY',
                'detail2': 'New bar opening. Needs liquor liability insurance, general liability, property coverage.',
                'time': '4 hr ago',
            },
            {
                'pill': 'Permit', 'pill_color': 'amber', 'pill_icon': 'bi-file-earmark-check',
                'urgency': 'warm',
                'title': 'New Building Permit — 8-Unit Residential',
                'detail1': 'Address: 55-12 Myrtle Ave, Ridgewood, Queens NY',
                'detail2': 'New construction. Developer needs builder\'s risk insurance, general liability, umbrella.',
                'time': '6 hr ago',
            },
        ],
        'sources': [
            {'name': 'Business Filings (DOS)', 'icon': 'bi-building', 'desc': 'Every new LLC and corporation needs business insurance'},
            {'name': 'ACRIS Property Sales', 'icon': 'bi-house-door', 'desc': 'New homeowners need homeowner\'s insurance before closing'},
            {'name': 'Liquor License Applications', 'icon': 'bi-cup-straw', 'desc': 'Bars and restaurants need liquor liability insurance'},
            {'name': 'NYC DOB Permits', 'icon': 'bi-file-earmark-check', 'desc': 'Construction projects need builder\'s risk and liability coverage'},
        ],
    },
}

INDUSTRY_LIST = [
    INDUSTRIES[slug] for slug in [
        'commercial-cleaning', 'plumbing', 'electrical', 'hvac',
        'general-contracting', 'pest-control', 'landscaping',
        'roofing', 'moving', 'insurance',
    ]
]


def industry_index(request):
    return render(request, 'industries/index.html', {
        'industries': INDUSTRY_LIST,
    })


def industry_detail(request, slug):
    industry = INDUSTRIES.get(slug)
    if not industry:
        raise Http404
    return render(request, 'industries/detail.html', {
        'industry': industry,
        'industries': INDUSTRY_LIST,
    })
