# Generated by Django 6.0.3 on 2026-03-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='platform',
            field=models.CharField(choices=[('craigslist', 'Craigslist'), ('reddit', 'Reddit'), ('patch', 'Patch.com'), ('houzz', 'Houzz'), ('alignable', 'Alignable'), ('google_qna', 'Google Q&A'), ('google_reviews', 'Google Reviews'), ('yelp_review', 'Yelp Review'), ('angi_review', 'Angi Review'), ('thumbtack', 'Thumbtack'), ('porch', 'Porch'), ('citydata', 'City-Data Forum'), ('biggerpockets', 'BiggerPockets'), ('facebook', 'Facebook'), ('nextdoor', 'Nextdoor'), ('twitter', 'Twitter/X'), ('manual', 'Manual Entry')], max_length=50),
        ),
    ]
