# Generated by Django 6.0.3 on 2026-03-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lead_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredLocalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('community_section_url', models.URLField(blank=True)),
                ('scrape_pattern', models.CharField(choices=[('wordpress_comments', 'WordPress Comments'), ('discourse', 'Discourse Forum'), ('custom_html', 'Custom HTML')], default='custom_html', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per site. Keys: article_list, article_link, article_title, article_date, article_author, article_body, comment_list, comment_body')),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='platform',
            field=models.CharField(choices=[('craigslist', 'Craigslist'), ('reddit', 'Reddit'), ('patch', 'Patch.com'), ('houzz', 'Houzz'), ('alignable', 'Alignable'), ('google_qna', 'Google Q&A'), ('google_reviews', 'Google Reviews'), ('yelp_review', 'Yelp Review'), ('angi_review', 'Angi Review'), ('thumbtack', 'Thumbtack'), ('porch', 'Porch'), ('citydata', 'City-Data Forum'), ('biggerpockets', 'BiggerPockets'), ('local_news', 'Local News/Blog'), ('parent_community', 'Parent Community'), ('trade_forum', 'Trade Forum'), ('facebook', 'Facebook'), ('nextdoor', 'Nextdoor'), ('twitter', 'Twitter/X'), ('manual', 'Manual Entry')], max_length=50),
        ),
    ]
