# Generated by Django 6.0.3 on 2026-03-07 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monitoredlocalsite_alter_lead_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredFacebookGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('group_id', models.CharField(help_text='Numeric Facebook group ID', max_length=100, unique=True)),
                ('url', models.URLField(help_text='Full group URL, e.g. https://www.facebook.com/groups/123456')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Service keywords to match inside this group')),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('posts_scraped', models.IntegerField(default=0)),
                ('leads_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, help_text='Owner business; leave blank for shared/global groups', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_groups', to='core.businessprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
