# Generated by Django 6.0.3 on 2026-03-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monitor_run_email_log_unsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('category', 'Category Default'), ('subcategory', 'Subcategory'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.businessprofile')),
            ],
            options={
                'ordering': ['source', 'keyword'],
                'unique_together': {('business', 'keyword')},
            },
        ),
    ]
