# Generated by Django 6.0.3 on 2026-03-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='email_signature',
            field=models.TextField(blank=True, help_text='Your preferred email sign-off (name, title, phone, website).'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='email_style_guide',
            field=models.TextField(blank=True, help_text='Describe how you want outreach emails written (tone, style, key points).'),
        ),
    ]
