# Generated by Django 6.0.3 on 2026-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expand_platform_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Los Angeles County Building Permits', max_length=200)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('source_url', models.URLField(help_text='URL of the permit search/listing page')),
                ('scrape_method', models.CharField(choices=[('html_table', 'HTML Table'), ('pdf_report', 'PDF Report'), ('api', 'API'), ('csv_download', 'CSV Download')], default='html_table', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per source. Keys: table_selector, row_selector, permit_type, address, filing_date, estimated_value, owner_name, contractor_name, status, next_page')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API-specific config: endpoint, params, headers, pagination key, result key')),
                ('schedule', models.CharField(default='weekly', max_length=20)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['state', 'county'],
                'unique_together': {('county', 'state')},
            },
        ),
        migrations.CreateModel(
            name='PropertyTransferSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Los Angeles County Recorder', max_length=200)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('source_url', models.URLField(help_text='URL of the property transfer search/listing page')),
                ('scrape_method', models.CharField(choices=[('html_table', 'HTML Table'), ('api', 'API'), ('csv_download', 'CSV Download'), ('apify_zillow', 'Apify Zillow Scraper')], default='html_table', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per source. Keys: table_selector, row_selector, address, sale_date, sale_price, buyer_name, property_type, square_footage, next_page')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API/Apify-specific config: endpoint, params, search_area, property_type_filter')),
                ('schedule', models.CharField(default='weekly', max_length=20)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['state', 'county'],
                'unique_together': {('county', 'state')},
            },
        ),
    ]
