# Generated by Django 6.0.3 on 2026-03-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_permit_property_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateBusinessFilingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=2, unique=True)),
                ('state_name', models.CharField(max_length=50)),
                ('source_url', models.URLField(help_text='URL of the state corporation search portal')),
                ('scrape_method', models.CharField(choices=[('html_table', 'HTML Table'), ('api', 'API'), ('csv_download', 'CSV Download')], default='html_table', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per source. Keys: table_selector, row_selector, business_name, filing_date, entity_type, registered_agent, address, status, next_page')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API-specific config: endpoint, params, headers, result_key')),
                ('search_params', models.JSONField(blank=True, default=dict, help_text='Default search parameters: date_range_days, entity_types, etc.')),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'State Business Filing Source',
                'verbose_name_plural': 'State Business Filing Sources',
                'ordering': ['state'],
            },
        ),
    ]
