# Generated by Django 6.0.3 on 2026-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_state_business_filing_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeViolationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. City of Houston Code Enforcement', max_length=200)),
                ('municipality', models.CharField(db_index=True, help_text='City or township name', max_length=200)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('source_url', models.URLField(help_text='URL of the code violation search/listing page')),
                ('scrape_method', models.CharField(choices=[('html_table', 'HTML Table'), ('api', 'API'), ('csv_download', 'CSV Download')], default='html_table', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per source. Keys: table_selector, row_selector, address, violation_type, violation_date, compliance_deadline, owner_name, status, next_page')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API-specific config: endpoint, params, headers, result_key')),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code Violation Source',
                'verbose_name_plural': 'Code Violation Sources',
                'ordering': ['state', 'municipality'],
                'unique_together': {('municipality', 'state')},
            },
        ),
        migrations.CreateModel(
            name='HealthInspectionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Los Angeles County Health Inspections', max_length=200)),
                ('jurisdiction', models.CharField(db_index=True, help_text='County or city name', max_length=200)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('source_url', models.URLField(help_text='URL of the inspection results page')),
                ('scrape_method', models.CharField(choices=[('html_table', 'HTML Table'), ('api', 'API'), ('csv_download', 'CSV Download')], default='html_table', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per source. Keys: table_selector, row_selector, restaurant_name, address, inspection_date, score, grade, violations, next_page')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API-specific config: endpoint, params, headers, result_key')),
                ('failing_threshold', models.IntegerField(default=70, help_text='Score below this is considered a failure (default: 70)')),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health Inspection Source',
                'verbose_name_plural': 'Health Inspection Sources',
                'ordering': ['state', 'jurisdiction'],
                'unique_together': {('jurisdiction', 'state')},
            },
        ),
        migrations.CreateModel(
            name='LicensingBoardSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. California CSLB Contractor Licenses', max_length=200)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('license_type', models.CharField(db_index=True, help_text='e.g. plumbing, electrical, general contractor, HVAC', max_length=100)),
                ('source_url', models.URLField(help_text='URL of the license search/lookup page')),
                ('scrape_method', models.CharField(choices=[('html_table', 'HTML Table'), ('api', 'API'), ('csv_download', 'CSV Download')], default='html_table', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per source. Keys: table_selector, row_selector, contractor_name, license_number, license_type, expiration_date, status, business_address, next_page')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API-specific config: endpoint, params, headers, result_key')),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Licensing Board Source',
                'verbose_name_plural': 'Licensing Board Sources',
                'ordering': ['state', 'license_type'],
                'unique_together': {('state', 'license_type')},
            },
        ),
    ]
