# Generated by Django 6.0.3 on 2026-03-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_code_violation_health_inspection_licensing_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtRecordSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Harris County Court Records', max_length=200)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('source_url', models.URLField(help_text='URL of the court record search portal')),
                ('scrape_method', models.CharField(choices=[('html_table', 'HTML Table'), ('api', 'API'), ('csv_download', 'CSV Download')], default='html_table', max_length=50)),
                ('css_selectors', models.JSONField(blank=True, default=dict, help_text='Custom CSS selectors per source. Keys: table_selector, row_selector, address, filing_date, case_number, plaintiff, property_type, status, next_page')),
                ('api_config', models.JSONField(blank=True, default=dict, help_text='API-specific config: endpoint, params, headers, result_key')),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Court Record Source',
                'verbose_name_plural': 'Court Record Sources',
                'ordering': ['state', 'county'],
                'unique_together': {('county', 'state')},
            },
        ),
    ]
