# Generated by Django 6.0.3 on 2026-03-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_court_record_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='industry_group',
            field=models.CharField(choices=[('home_services', 'Home Services & Repair'), ('cleaning', 'Cleaning Services'), ('outdoor', 'Outdoor & Landscaping'), ('construction', 'Construction & Remodeling'), ('auto', 'Automotive'), ('professional', 'Professional Services'), ('healthcare', 'Healthcare & Wellness'), ('events', 'Events & Entertainment'), ('education', 'Education & Training'), ('pet', 'Pet Services'), ('senior', 'Senior Care'), ('technology', 'Technology')], default='home_services', help_text='Groups categories in the onboarding wizard', max_length=30),
        ),
    ]
