# Generated by Django 6.0.3 on 2026-03-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_industry_group_to_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='custom_from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='custom_from_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='custom_smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='custom_smtp_password_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted SMTP password. Use set_smtp_password() / get_smtp_password().'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='custom_smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='custom_smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='use_custom_smtp',
            field=models.BooleanField(default=False, help_text='Send outreach emails through your own SMTP server instead of our default.'),
        ),
    ]
