# Generated by Django 6.0.3 on 2026-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_custom_smtp_to_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10),
        ),
    ]
