# Generated by Django 6.0.3 on 2026-03-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
