# Generated by Django 6.0.3 on 2026-03-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_has_seen_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned')], default='unreviewed', max_length=20),
        ),
    ]
