# Generated by Django 6.0.3 on 2026-03-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_lead_confidence_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedGoogleBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, help_text='Google Places primary type or search category', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('business_status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('CLOSED_TEMPORARILY', 'Closed Temporarily'), ('CLOSED_PERMANENTLY', 'Closed Permanently')], default='OPERATIONAL', max_length=30)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('google_maps_url', models.URLField(blank=True, max_length=500)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracked Google Business',
                'verbose_name_plural': 'Tracked Google Businesses',
                'ordering': ['-first_seen'],
            },
        ),
    ]
