# Generated by Django 6.0.3 on 2026-03-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_tracked_google_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='platform',
            field=models.CharField(choices=[('craigslist', 'Craigslist'), ('reddit', 'Reddit'), ('patch', 'Patch.com'), ('houzz', 'Houzz'), ('alignable', 'Alignable'), ('google_qna', 'Google Q&A'), ('google_reviews', 'Google Reviews'), ('google_maps', 'Google Maps'), ('yelp_review', 'Yelp Review'), ('angi_review', 'Angi Review'), ('thumbtack', 'Thumbtack'), ('porch', 'Porch'), ('citydata', 'City-Data Forum'), ('biggerpockets', 'BiggerPockets'), ('local_news', 'Local News/Blog'), ('parent_community', 'Parent Community'), ('trade_forum', 'Trade Forum'), ('facebook', 'Facebook'), ('nextdoor', 'Nextdoor'), ('twitter', 'Twitter/X'), ('tiktok', 'TikTok'), ('quora', 'Quora'), ('threads', 'Threads'), ('fb_marketplace', 'FB Marketplace'), ('trustpilot', 'Trustpilot'), ('instagram', 'Instagram'), ('bbb', 'BBB'), ('permit', 'Building Permit'), ('property_sale', 'Property Sale'), ('business_filing', 'Business Filing'), ('weather_alert', 'Weather Alert'), ('code_violation', 'Code Violation'), ('eviction_filing', 'Eviction Filing'), ('health_inspection', 'Health Inspection'), ('license_expiry', 'License Expiry'), ('manual', 'Manual Entry')], max_length=50),
        ),
    ]
