# Generated by Django 6.0.3 on 2026-03-12 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_google_maps_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedcompetitor',
            name='business_status',
            field=models.CharField(blank=True, default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='trackedcompetitor',
            name='previous_google_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedcompetitor',
            name='previous_review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedcompetitor',
            name='rating_trend',
            field=models.CharField(blank=True, choices=[('improving', 'Improving'), ('declining', 'Declining'), ('flat', 'Flat')], default='flat', max_length=10),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('lead', 'Inbound Lead'), ('outreach', 'Outreach Prospect'), ('manual', 'Manual Entry'), ('referral', 'Referral')], default='lead', max_length=20)),
                ('source_platform', models.CharField(blank=True, max_length=50)),
                ('pipeline_stage', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('service_needed', models.CharField(blank=True, max_length=200)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('won_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.businessprofile')),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.leadassignment')),
                ('source_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.lead')),
                ('source_prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.prospectbusiness')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('service_needed', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.businessprofile')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.contact')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('call', 'Phone Call'), ('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_replied', 'Email Replied'), ('meeting', 'Meeting'), ('quoted', 'Quote Sent'), ('won', 'Deal Won'), ('lost', 'Deal Lost'), ('follow_up', 'Follow-up Set'), ('stage_change', 'Stage Changed'), ('lead_found', 'Lead Discovered'), ('appointment', 'Appointment')], max_length=20)),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outreach_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.outreachemail')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.contact')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
