# Generated by Django 6.0.3 on 2026-03-12 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_crm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcampaign',
            name='ai_estimated_cost_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='ai_total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='customer_custom_instructions',
            field=models.TextField(blank=True, help_text='Custom instructions for AI email generation (e.g. "mention our 20 years experience")'),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='daily_send_limit',
            field=models.IntegerField(default=15, help_text='New prospects per day (rest reserved for follow-ups)'),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='email_sequence_count',
            field=models.IntegerField(default=3, help_text='Number of emails in the sequence (1-3)'),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='email_style',
            field=models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('direct', 'Direct')], default='professional', max_length=20),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='emails_bounced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text="Customer's real email for replies", max_length=254),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='send_mode',
            field=models.CharField(choices=[('salessignal', 'SalesSignal Email'), ('gmail', 'Connected Gmail')], default='salessignal', max_length=20),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='sending_email',
            field=models.EmailField(blank=True, help_text='Email address to send from', max_length=254),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='target_category',
            field=models.CharField(blank=True, help_text='What kind of businesses to prospect (e.g. "property manager", "restaurant")', max_length=200),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='target_location',
            field=models.CharField(blank=True, help_text='City, zip, or area to target', max_length=200),
        ),
        migrations.CreateModel(
            name='OutreachProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('google_maps', 'Google Maps'), ('manual_upload', 'Manual Upload'), ('customer_list', 'Customer List'), ('no_website_lead', 'No Website Lead')], default='google_maps', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('email1_sent', 'Email 1 Sent'), ('email2_sent', 'Email 2 Sent'), ('email3_sent', 'Email 3 Sent'), ('replied', 'Replied'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('bounced', 'Bounced')], default='new', max_length=20)),
                ('email1_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email2_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email3_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email1_opened', models.BooleanField(default=False)),
                ('email2_opened', models.BooleanField(default=False)),
                ('email3_opened', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_text', models.TextField(blank=True)),
                ('reply_classification', models.CharField(blank=True, help_text='AI classification: interested/not_interested/question/out_of_office', max_length=20)),
                ('enrichment_data', models.JSONField(blank=True, default=dict, help_text='Scraped website info, owner name, business details for AI personalization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='core.outreachcampaign')),
                ('prospect_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_prospects', to='core.prospectbusiness')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'contact_email')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(default=1, help_text='1=intro, 2=follow-up day 3, 3=final touch day 7')),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('ai_model_used', models.CharField(blank=True, help_text='Which AI model generated this email', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('opened', 'Opened'), ('replied', 'Replied'), ('bounced', 'Bounced')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, help_text='Unique ID for open/click tracking', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_emails', to='core.outreachprospect')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('prospect', 'sequence_number')},
            },
        ),
    ]
