# Generated by Django 6.0.3 on 2026-03-12 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_outreach_campaign_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('territory', models.CharField(blank=True, help_text='Territory description, e.g. "Nassau County plumbers"', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('daily_call_goal', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salespeople',
            },
        ),
        migrations.CreateModel(
            name='SalesProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('service_category', models.CharField(blank=True, help_text='e.g. plumber, electrician, cleaner', max_length=100)),
                ('source', models.CharField(choices=[('google_maps_scan', 'Google Maps Scan'), ('manual_entry', 'Manual Entry'), ('referral', 'Referral'), ('inbound', 'Inbound')], default='manual_entry', max_length=20)),
                ('source_lead_id', models.IntegerField(blank=True, help_text='ID of the Lead record this was imported from', null=True)),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('google_review_count', models.IntegerField(blank=True, null=True)),
                ('has_website', models.BooleanField(default=True)),
                ('pipeline_stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('callback', 'Callback'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new', max_length=20)),
                ('lost_reason', models.CharField(blank=True, choices=[('too_expensive', 'Too Expensive'), ('not_interested', 'Not Interested'), ('using_competitor', 'Using Competitor'), ('no_response', 'No Response'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('estimated_monthly_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly subscription value', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_origin', to='core.businessprofile')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='core.salesperson')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('voicemail', 'Voicemail'), ('email', 'Email'), ('demo', 'Demo'), ('proposal', 'Proposal'), ('follow_up', 'Follow-up'), ('note', 'Note'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('call_duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('outcome', models.CharField(blank=True, choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.salesperson')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.salesprospect')),
            ],
            options={
                'verbose_name_plural': 'Sales Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
