# Generated by Django 6.0.3 on 2026-03-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_public_records_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_business',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, help_text='Sub-region: borough, county, city', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_group',
            field=models.CharField(choices=[('public_records', 'Public Records'), ('social_media', 'Social Media'), ('reviews', 'Review Sites'), ('weather', 'Weather/Events')], db_index=True, default='public_records', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_type',
            field=models.CharField(blank=True, choices=[('violations', 'DOB Violations'), ('permits', 'DOB Permits'), ('permits_now', 'DOB Permits (NOW)'), ('property_sales', 'Property Sales'), ('health_inspections', 'Health Inspections'), ('liquor_licenses', 'Liquor Licenses'), ('business_filings', 'Business Filings'), ('reddit', 'Reddit'), ('nextdoor', 'Nextdoor'), ('facebook', 'Facebook Groups'), ('google_reviews', 'Google Reviews'), ('no_website', 'No Website Detected'), ('google_qa', 'Google Q&A'), ('noaa', 'NOAA Weather')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, db_index=True, default='NY', help_text='Two-letter state code', max_length=2),
        ),
    ]
