# Generated by Django 6.0.3 on 2026-03-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_lead_repository_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL slug: /demo/joes-plumbing/', max_length=200, unique=True)),
                ('prospect_business_name', models.CharField(max_length=200)),
                ('prospect_owner_name', models.CharField(blank=True, max_length=200)),
                ('prospect_phone', models.CharField(blank=True, max_length=20)),
                ('prospect_email', models.EmailField(blank=True, max_length=254)),
                ('prospect_trade', models.CharField(help_text='Plumbing, Cleaning, Electrical, etc.', max_length=100)),
                ('prospect_city', models.CharField(max_length=100)),
                ('prospect_state', models.CharField(default='NY', max_length=2)),
                ('video_url', models.URLField(help_text='YouTube unlisted URL or HeyGen direct link')),
                ('video_thumbnail_url', models.URLField(blank=True, help_text='Optional thumbnail image URL')),
                ('headline', models.CharField(blank=True, help_text="Custom headline. Default: '{business_name} — See What We Found'", max_length=300)),
                ('custom_message', models.TextField(blank=True, help_text="Message shown below the video. E.g. 'We found 47 people in your area looking for a plumber this week.'")),
                ('cta_text', models.CharField(default='Book a Call', help_text='Button text', max_length=100)),
                ('cta_url', models.URLField(blank=True, help_text='Where the CTA button links. Leave blank for default contact form.')),
                ('customer_business_name', models.CharField(blank=True, help_text="The paying customer's business name to feature in the page", max_length=200)),
                ('customer_phone', models.CharField(blank=True, help_text="Customer's phone for the prospect to call", max_length=20)),
                ('customer_website', models.URLField(blank=True)),
                ('trigger_type', models.CharField(blank=True, choices=[('health_violation', 'Health Inspection Violation'), ('building_violation', 'Building Violation'), ('new_business', 'New Business Filing'), ('property_sale', 'Property Sale'), ('permit_filed', 'Permit Filed'), ('social_request', 'Social Media Request'), ('no_website', 'No Website Detected'), ('bad_reviews', 'Low Google Reviews'), ('competitor_issue', 'Competitor Issue'), ('custom', 'Custom Outreach')], default='custom', max_length=50)),
                ('trigger_detail', models.TextField(blank=True, help_text="Specific trigger info: 'Health inspection score 42, critical violation for pest issues'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('video_plays', models.IntegerField(default=0)),
                ('cta_clicks', models.IntegerField(default=0)),
                ('prospect_responded', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('responded', 'Responded'), ('converted', 'Converted'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('customer', models.ForeignKey(blank=True, help_text='If created on behalf of a paying customer, select them here', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
