# Generated by Django 6.0.3 on 2026-03-20 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_prospectvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('opted_out_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_type',
            field=models.CharField(blank=True, choices=[('violations', 'DOB Violations'), ('permits', 'DOB Permits'), ('permits_now', 'DOB Permits (NOW)'), ('property_sales', 'Property Sales'), ('health_inspections', 'Health Inspections'), ('liquor_licenses', 'Liquor Licenses'), ('business_filings', 'Business Filings'), ('reddit', 'Reddit'), ('nextdoor', 'Nextdoor'), ('facebook', 'Facebook Groups'), ('google_reviews', 'Google Reviews'), ('no_website', 'No Website Detected'), ('google_qa', 'Google Q&A'), ('noaa', 'NOAA Weather'), ('prospect_video', 'Prospect Video Intake')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('completed', 'Completed'), ('no-answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('voicemail_transcription', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback', 'Callback Requested'), ('wrong_number', 'Wrong Number'), ('no_answer', 'No Answer'), ('left_voicemail', 'Left Voicemail'), ('appointment_booked', 'Appointment Booked')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='core.lead')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='core.salesperson')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(blank=True, db_index=True, max_length=100)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_number', models.CharField(db_index=True, max_length=20)),
                ('to_number', models.CharField(db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('is_yes_response', models.BooleanField(default=False)),
                ('is_opt_out', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='core.lead')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='core.salesperson')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
