# Generated by Django 6.0.3 on 2026-03-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_call_center_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('emergency_keywords', models.TextField(blank=True, help_text='Comma-separated: emergency plumber, 24 hour plumber, plumber near me')),
                ('service_keywords', models.TextField(blank=True, help_text='Comma-separated: drain cleaning, water heater repair, toilet repair')),
                ('pain_points', models.TextField(blank=True, help_text='Common customer problems: burst pipe flooding, no hot water')),
                ('category_type', models.CharField(choices=[('home_service', 'Home Service'), ('commercial_service', 'Commercial Service'), ('professional', 'Professional Service'), ('emergency', 'Emergency Service')], default='home_service', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Trade Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('area_type', models.CharField(choices=[('borough', 'Borough'), ('city', 'City'), ('county', 'County'), ('town', 'Town'), ('village', 'Village'), ('neighborhood', 'Neighborhood'), ('zip', 'ZIP Code')], default='city', max_length=20)),
                ('state', models.CharField(default='NY', max_length=2)),
                ('state_full', models.CharField(default='New York', max_length=50)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('neighboring_areas', models.ManyToManyField(blank=True, to='core.servicearea')),
                ('parent_area', models.ForeignKey(blank=True, help_text='Parent area (e.g. Queens -> New York City)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.servicearea')),
            ],
            options={
                'ordering': ['state', 'name'],
                'unique_together': {('slug', 'state')},
            },
        ),
        migrations.CreateModel(
            name='ServiceLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('salessignal', 'SalesSignal Owned'), ('customer', 'Customer Branded')], default='salessignal', max_length=20)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=200)),
                ('branded_business_name', models.CharField(blank=True, max_length=200)),
                ('branded_phone', models.CharField(blank=True, max_length=20)),
                ('branded_email', models.EmailField(blank=True, max_length=254)),
                ('branded_website', models.URLField(blank=True)),
                ('branded_logo_url', models.URLField(blank=True)),
                ('branded_tagline', models.CharField(blank=True, max_length=200)),
                ('branded_years_in_business', models.IntegerField(blank=True, null=True)),
                ('branded_license_number', models.CharField(blank=True, max_length=100)),
                ('branded_google_reviews_url', models.URLField(blank=True)),
                ('branded_star_rating', models.FloatField(blank=True, null=True)),
                ('branded_review_count', models.IntegerField(blank=True, null=True)),
                ('signalwire_phone', models.CharField(blank=True, max_length=20)),
                ('forward_to_phone', models.CharField(blank=True, max_length=20)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('h1_headline', models.CharField(blank=True, max_length=200)),
                ('hero_subheadline', models.CharField(blank=True, max_length=300)),
                ('show_live_stats', models.BooleanField(default=True)),
                ('services_offered', models.TextField(blank=True, help_text='One per line')),
                ('about_section', models.TextField(blank=True)),
                ('faq_section', models.JSONField(blank=True, default=list)),
                ('form_submissions', models.IntegerField(default=0)),
                ('phone_calls', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='core.servicearea')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_landing_pages', to='core.businessprofile')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='core.tradecategory')),
            ],
            options={
                'ordering': ['trade__name', 'area__name'],
                'unique_together': {('trade', 'area', 'page_type', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='ServicePageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('problem_description', models.TextField()),
                ('urgency', models.CharField(choices=[('emergency', 'Emergency — Need help now'), ('today', 'Today'), ('this_week', 'This week'), ('getting_quotes', 'Just getting quotes')], default='today', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('form', 'Web Form'), ('phone', 'Phone Call')], default='form', max_length=20)),
                ('routed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.servicelandingpage')),
                ('routed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_page_leads', to='core.businessprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
