# Generated by Django 6.0.3 on 2026-03-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_service_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_payment', 'Pending Payment'), ('pending_plan', 'Pending Plan Selection'), ('pending_verification', 'Pending Email Verification'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='biggest_challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='created_by_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='desired_customers_per_month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='marketing_budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='marketing_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='num_employees',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='temp_password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='years_in_business',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('none', 'No Plan'), ('outreach', 'Outreach ($149/mo)'), ('growth', 'Growth ($349/mo)'), ('dominate', 'Dominate ($649/mo)'), ('concierge', 'Concierge (Custom)'), ('custom_outbound', 'Custom Outbound (Custom)')], default='none', max_length=20),
        ),
    ]
