# Generated by Django 6.0.3 on 2026-03-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='commission_notes',
            field=models.TextField(blank=True, help_text='Commission structure details'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='trade_specialization',
            field=models.CharField(blank=True, help_text='Trade focus, e.g. "plumbers, electricians" or blank for all trades', max_length=200),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='territory',
            field=models.CharField(blank=True, help_text='Territory description, e.g. "Nassau County, Suffolk County"', max_length=300),
        ),
    ]
