# Generated by Django 6.0.3 on 2026-03-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_salesperson_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=10),
        ),
    ]
