# Generated by Django 6.0.3 on 2026-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_theme_default_light'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-event_date', '-discovered_at']},
        ),
        migrations.AddField(
            model_name='lead',
            name='event_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Actual date of the event (violation issued, permit filed, etc.)', null=True),
        ),
    ]
