# Generated by Django 6.0.3 on 2026-03-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_event_date_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enrichment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_status',
            field=models.CharField(choices=[('not_enriched', 'Not Enriched'), ('enriched', 'Enriched'), ('enrichment_failed', 'Enrichment Failed'), ('manually_enriched', 'Manually Enriched')], db_index=True, default='not_enriched', max_length=20),
        ),
    ]
