# Generated by Django 6.0.3 on 2026-03-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_enrichment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(help_text='HTML content')),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('author', models.CharField(default='SalesSignal AI Team', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('featured_image_url', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=300)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
