# Generated by Django 6.0.3 on 2026-03-24 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_blog_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger', models.CharField(choices=[('lead_status_changed', 'Lead Status Changed'), ('prospect_stage_changed', 'Prospect Stage Changed'), ('email_replied', 'Email Replied'), ('email_opened', 'Email Opened'), ('call_completed', 'Call Completed'), ('no_response_days', 'No Response After X Days'), ('lead_assigned', 'Lead Assigned'), ('appointment_booked', 'Appointment Booked'), ('form_submitted', 'Form Submitted')], max_length=30)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='JSON conditions, e.g. {"from_status": "new", "to_status": "contacted"}')),
                ('actions', models.JSONField(default=list, help_text='Ordered list of action dicts: [{"type": "send_email", "template": "...", "delay_days": 2}]')),
                ('times_triggered', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='core.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by_model', models.CharField(blank=True, max_length=50)),
                ('triggered_by_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('waiting', 'Waiting (delay)')], default='pending', max_length=20)),
                ('current_action_index', models.IntegerField(default=0)),
                ('resume_at', models.DateTimeField(blank=True, null=True)),
                ('result_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.workflowrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
