# Generated by Django 6.0.3 on 2026-03-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='recording_duration',
            field=models.IntegerField(blank=True, help_text='Recording duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='recording_sid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
