# Generated by Django 6.0.3 on 2026-03-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_call_recording_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='trial_leads_remaining',
            field=models.IntegerField(default=10, help_text='Free lead views remaining for trial users'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Free Trial'), ('pending_payment', 'Pending Payment'), ('pending_plan', 'Pending Plan Selection'), ('pending_verification', 'Pending Email Verification'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=30),
        ),
    ]
