# Generated by Django 6.0.3 on 2026-03-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_trial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesactivity',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesactivity',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesactivity',
            name='task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesactivity',
            name='task_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('voicemail', 'Voicemail'), ('email', 'Email'), ('demo', 'Demo'), ('proposal', 'Proposal'), ('follow_up', 'Follow-up'), ('note', 'Note'), ('task', 'Task'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], max_length=20),
        ),
    ]
