# Generated by Django 6.0.3 on 2026-03-26 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_sales_task_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('script_type', models.CharField(choices=[('violation', 'Violation Lead'), ('property_sale', 'Property Sale Lead'), ('no_website', 'No Website Prospect'), ('health_inspection', 'Health Inspection Lead'), ('business_filing', 'New Business Filing'), ('general', 'General Outreach'), ('followup', 'Follow-up Call'), ('appointment', 'Appointment Setting')], max_length=30)),
                ('opening', models.TextField(help_text='Opening statement')),
                ('talking_points', models.JSONField(default=list, help_text='List of talking points')),
                ('qualification_questions', models.JSONField(default=list, help_text='Questions to qualify the lead')),
                ('objection_handlers', models.JSONField(default=dict, help_text='Common objections and responses')),
                ('closing', models.TextField(blank=True, help_text='Closing statement')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['script_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('introduction', 'Introduction'), ('followup', 'Follow-up'), ('quote', 'Quote/Proposal'), ('appointment', 'Appointment Confirmation'), ('thankyou', 'Thank You'), ('custom', 'Custom')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
