# Generated by Django 6.0.3 on 2026-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_email_templates_call_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('goal', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], default='queued', max_length=20)),
                ('result', models.TextField(blank=True)),
                ('steps_taken', models.IntegerField(default=0)),
                ('leads_found', models.IntegerField(default=0)),
                ('mission_log', models.JSONField(default=list)),
                ('triggered_by', models.CharField(blank=True, help_text='sms, web, cron, or username', max_length=100)),
                ('triggered_from', models.CharField(blank=True, help_text='Phone number or IP', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
