# Generated by Django 6.0.3 on 2026-03-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_agent_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('alerted', 'Alert Sent'), ('viewed', 'Viewed'), ('contacted', 'Contacted'), ('quoted', 'Quote Sent'), ('won', 'Won'), ('lost', 'Lost'), ('expired', 'Expired'), ('dismissed', 'Dismissed')], default='new', max_length=20),
        ),
    ]
