# Generated by Django 6.0.3 on 2026-03-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_lead_dismissed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('none', 'No Plan'), ('outreach', 'Starter AI ($599/mo)'), ('growth', 'Growth AI ($1,199/mo)'), ('dominate', 'Dominate AI ($1,999/mo)'), ('concierge', 'Concierge (Custom)'), ('custom_outbound', 'Custom Outbound (Custom)')], default='none', max_length=20),
        ),
    ]
