# Generated by Django 6.0.3 on 2026-04-01 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_businessprofile_subscription_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Page headline', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Shown below the headline')),
                ('available_days', models.JSONField(blank=True, default=list, help_text='List of weekday ints: 0=Mon .. 6=Sun')),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('slot_duration_minutes', models.IntegerField(default=30)),
                ('max_bookings_per_day', models.IntegerField(default=10)),
                ('accent_color', models.CharField(default='#0D9488', max_length=7)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('page_views', models.IntegerField(default=0)),
                ('bookings_made', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_needed', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('confirmation_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment')),
                ('booking_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookingpage')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('google_review_url', models.URLField(blank=True, help_text='Direct Google review link for the business', max_length=500)),
                ('yelp_review_url', models.URLField(blank=True, max_length=500)),
                ('sms_template', models.TextField(default="Hi {name}! Thanks for choosing {business}. We'd love your feedback — would you mind leaving us a quick Google review? {link}", help_text='Variables: {name}, {business}, {link}')),
                ('email_subject', models.CharField(default='How did we do?', max_length=200)),
                ('email_template', models.TextField(default="Hi {name},\n\nThank you for choosing {business}! We hope you were satisfied with our service.\n\nIf you have a moment, we'd really appreciate a quick review:\n{link}\n\nThank you!\n{business}", help_text='Variables: {name}, {business}, {link}')),
                ('channel', models.CharField(choices=[('sms', 'SMS Only'), ('email', 'Email Only'), ('both', 'SMS + Email')], default='sms', max_length=10)),
                ('auto_send_on_won', models.BooleanField(default=False, help_text='Automatically send when a contact stage becomes "won"')),
                ('delay_hours', models.IntegerField(default=24, help_text='Hours to wait after trigger before sending')),
                ('total_sent', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoicemailDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audio_url', models.URLField(help_text='URL to the pre-recorded audio file (MP3/WAV)', max_length=500)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='Null = system-wide template', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoicemailDropLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=20)),
                ('call_sid', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('calling', 'Calling'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salesprospect')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salesperson')),
                ('voicemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voicemaildrop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_via', models.CharField(blank=True, max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sid', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('clicked', 'Clicked'), ('reviewed', 'Reviewed'), ('failed', 'Failed'), ('opted_out', 'Opted Out')], default='pending', max_length=20)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reviewcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
