# Generated by Django 6.0.3 on 2026-04-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_lead_intent_classification_curation'),
    ]

    operations = [
    ]
