# Generated by Django 6.0.3 on 2026-04-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_bookingpage_bookingsubmission_reviewcampaign_and_more'),
        ('core', '0045_data_sources_and_engagement'),
    ]

    operations = [
    ]
