# Generated by Django 6.0.3 on 2026-04-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_data_sources_and_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcandidate',
            name='gemini_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetcandidate',
            name='lead_value_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='datasetcandidate',
            name='recommended_filters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='datasetcandidate',
            name='service_matches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
