# Generated by Django 6.0.3 on 2026-04-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_20260410_1126'),
        ('core', '0046_scout_gemini_fields'),
    ]

    operations = [
    ]
