# Generated by Django 6.0.3 on 2026-04-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20260411_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('none', 'No Plan'), ('trial', 'Free Trial'), ('starter_ai', 'Starter — AI Automated'), ('growth_ai', 'Growth — AI Automated'), ('dominate_ai', 'Dominate — AI Automated'), ('closer_ai', 'Closer — AI Automated'), ('full_service_ai', 'Full Service — AI + Human'), ('starter_human', 'Starter — Human + AI'), ('growth_human', 'Growth — Human + AI'), ('dominate_human', 'Dominate — Human + AI'), ('closer_human', 'Closer — Human + AI'), ('full_service_human', 'Full Service — Full Human'), ('custom', 'Custom / A La Carte'), ('outreach', 'Starter AI (Legacy)'), ('growth', 'Growth AI (Legacy)'), ('dominate', 'Dominate AI (Legacy)'), ('concierge', 'Concierge (Legacy)'), ('custom_outbound', 'Custom Outbound (Legacy)')], default='none', max_length=20),
        ),
    ]
