# Generated by Django 6.0.3 on 2026-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_update_tier_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source_type',
            field=models.CharField(blank=True, choices=[('violations', 'DOB Violations'), ('building_violations', 'Building Violations'), ('hpd_violations', 'HPD Violations'), ('ordinance_violations', 'Ordinance Violations'), ('ecb_summonses', 'ECB Summonses'), ('code_enforcement', 'Code Enforcement'), ('code_complaints', 'Code Complaints'), ('fire_violations', 'Fire Violations'), ('housing_violations', 'Housing Violations'), ('environmental_violations', 'Environmental Violations'), ('environmental_remediation', 'Environmental Remediation'), ('alcohol_violations', 'Alcohol Violations'), ('repeat_offender_violations', 'Repeat Offenders'), ('permits', 'DOB Permits'), ('permits_now', 'DOB Permits (NOW)'), ('building_permits', 'Building Permits'), ('construction_permits', 'Construction Permits'), ('electrical_permits', 'Electrical Permits'), ('trade_permits', 'Trade Permits'), ('boiler_permits', 'Boiler Permits'), ('mc_permits', 'MC Permits'), ('certificate_of_occupancy', 'Certificate of Occupancy'), ('permit_contacts', 'Permit Contacts'), ('property_sales', 'Property Sales'), ('business_filings', 'Business Filings'), ('license_expirations', 'License Expirations'), ('liquor_licenses', 'Liquor Licenses'), ('liquor_suspensions', 'Liquor Suspensions'), ('storage_tanks', 'Storage Tanks'), ('health_inspections', 'Health Inspections'), ('food_inspections', 'Food Inspections'), ('pool_inspections', 'Pool Inspections'), ('google_reviews', 'Google Reviews'), ('no_website', 'No Website Detected'), ('closed_business', 'Closed Business'), ('new_business', 'New Business'), ('google_qa', 'Google Q&A'), ('reddit', 'Reddit'), ('nextdoor', 'Nextdoor'), ('facebook', 'Facebook Groups'), ('noaa', 'NOAA Weather'), ('prospect_video', 'Prospect Video Intake')], db_index=True, max_length=50),
        ),
    ]
